import type { SkillLibraryEntry } from '../types/skill.js'

/**
 * 技能库 — 所有预定义技能
 * 接口模块化：每个技能通过 effects[] 定义效果链
 * 后续增加技能只需在此数组中追加条目
 */
export const SKILL_LIBRARY: readonly SkillLibraryEntry[] = [
  // ===== A级技能 (选4) =====
  {
    id: 'a01',
    name: '圣剑一闪',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗2MP，对单体造成25伤害，无视5点护盾。',
    cost: { mp: 2 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'damage', params: { value: 25, pierceShield: 5 } },
    ],
  },
  {
    id: 'a02',
    name: '守护结界',
    skillClass: 'A',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'on_damage',
    description: '受到伤害时，抵消15点伤害。冷却2回合。',
    cooldown: 2,
    targetType: 'self',
    effects: [
      { effectType: 'shield', params: { value: 15 } },
    ],
  },
  {
    id: 'a03',
    name: '生命汲取',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗3MP，对单体造成15伤害并回复等量HP。',
    cost: { mp: 3 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'damage', params: { value: 15 } },
      { effectType: 'heal', params: { value: 15, target: 'self' } },
    ],
  },
  {
    id: 'a04',
    name: '战术侦查',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗1MP，查看目标手牌数量和HP，并抽1张牌。',
    cost: { mp: 1 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'vision', params: { reveal: ['handCount', 'hp'] } },
      { effectType: 'draw', params: { count: 1, target: 'self' } },
    ],
  },
  {
    id: 'a05',
    name: '迅捷突袭',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗2MP，移动到相邻区域并对该区域一名玩家造成20伤害。',
    cost: { mp: 2 },
    cooldown: 1,
    targetType: 'single',
    effects: [
      { effectType: 'move', params: { type: 'adjacent' } },
      { effectType: 'damage', params: { value: 20 } },
    ],
    tags: ['movement', 'damage'],
  },
  {
    id: 'a06',
    name: '神圣护佑',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗3MP，为自身附加30点护盾，持续2回合。',
    cost: { mp: 3 },
    cooldown: 2,
    targetType: 'self',
    effects: [
      { effectType: 'shield', params: { value: 30, duration: 2 } },
    ],
  },
  {
    id: 'a07',
    name: '命运抽签',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗1MP，从牌堆抽3张牌，然后弃1张。',
    cost: { mp: 1 },
    cooldown: 1,
    targetType: 'self',
    effects: [
      { effectType: 'draw', params: { count: 3, target: 'self' } },
      { effectType: 'discard', params: { count: 1, target: 'self', choice: 'player' } },
    ],
  },
  {
    id: 'a08',
    name: '破甲一击',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗2MP，对单体造成15伤害并移除目标所有护盾。',
    cost: { mp: 2 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'removeShield', params: {} },
      { effectType: 'damage', params: { value: 15 } },
    ],
  },
  {
    id: 'a09',
    name: '烽火连天',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗4MP，对当前区域所有敌人造成15伤害。',
    cost: { mp: 4 },
    cooldown: 2,
    targetType: 'area',
    effects: [
      { effectType: 'damage', params: { value: 15, aoe: true } },
    ],
  },
  {
    id: 'a10',
    name: '战地救护',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗2MP，回复自身或同区域友军30HP。',
    cost: { mp: 2 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'heal', params: { value: 30 } },
    ],
  },
  {
    id: 'a11',
    name: '暗影潜行',
    skillClass: 'A',
    rarity: 'rare',
    type: 'triggered',
    triggerTiming: 'on_move',
    description: '移动后进入隐匿状态，下次受击前不可被侦查发现。冷却3回合。',
    cooldown: 3,
    targetType: 'self',
    effects: [
      { effectType: 'stealth', params: { duration: 'until_hit' } },
    ],
    tags: ['stealth'],
  },
  {
    id: 'a12',
    name: '反击风暴',
    skillClass: 'A',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'on_damage',
    description: '受到击牌伤害时，自动对攻击者反弹10伤害。冷却1回合。',
    cooldown: 1,
    targetType: 'self',
    effects: [
      { effectType: 'reflect', params: { value: 10 } },
    ],
  },

  // ===== B级技能 (选2) =====
  {
    id: 'b01',
    name: '坚韧意志',
    skillClass: 'B',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'on_damage',
    description: 'HP低于30%时，受到的伤害减少5点。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'damageReduction', params: { value: 5, condition: 'hp_below_30%' } },
    ],
  },
  {
    id: 'b02',
    name: '资源回收',
    skillClass: 'B',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'round_start',
    description: '每回合开始时，从弃牌堆随机回收1张牌到手牌。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'retrieveDiscard', params: { count: 1, random: true } },
    ],
  },
  {
    id: 'b03',
    name: '先手之利',
    skillClass: 'B',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '战斗阶段中，你的出击优先级+1。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'modifyPriority', params: { value: 1 } },
    ],
  },
  {
    id: 'b04',
    name: '补给线',
    skillClass: 'B',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'round_end',
    description: '回合结束时，若手牌少于3张，抽牌至3张。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'draw', params: { fillTo: 3, condition: 'hand_below_3' } },
    ],
  },
  {
    id: 'b05',
    name: '地利之势',
    skillClass: 'B',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '在有己方阵地的区域战斗时，造成的伤害+5。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'damageBonus', params: { value: 5, condition: 'own_outpost_in_region' } },
    ],
  },
  {
    id: 'b06',
    name: '鹰眼洞察',
    skillClass: 'B',
    rarity: 'rare',
    type: 'triggered',
    triggerTiming: 'combat_before',
    description: '战斗开始前，可查看对手上一回合使用的技能。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'vision', params: { reveal: ['lastUsedSkills'] } },
    ],
  },
  {
    id: 'b07',
    name: '节能回路',
    skillClass: 'B',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'manual',
    description: '所有主动技能MP消耗-1（最低1）。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'mpReduction', params: { value: 1, minCost: 1 } },
    ],
  },
  {
    id: 'b08',
    name: '绝地反击',
    skillClass: 'B',
    rarity: 'rare',
    type: 'triggered',
    triggerTiming: 'on_damage',
    description: 'HP首次降至50%以下时，立即回复15HP并抽2张牌。每场战斗限1次。',
    cooldown: 0,
    charges: 1,
    targetType: 'self',
    effects: [
      { effectType: 'heal', params: { value: 15, target: 'self' } },
      { effectType: 'draw', params: { count: 2, target: 'self' } },
    ],
    tags: ['once_per_combat'],
  },
]

/** 按ID索引 */
export const SKILL_LIBRARY_MAP: Record<string, SkillLibraryEntry> =
  Object.fromEntries(SKILL_LIBRARY.map(s => [s.id, s]))

/** 按等级分组 */
export const A_CLASS_SKILLS = SKILL_LIBRARY.filter(s => s.skillClass === 'A')
export const B_CLASS_SKILLS = SKILL_LIBRARY.filter(s => s.skillClass === 'B')
