import type { SkillLibraryEntry } from '../types/skill.js'

/**
 * 技能库 — 所有预定义技能
 * 接口模块化：每个技能通过 effects[] 定义效果链
 * 后续增加技能只需在此数组中追加条目
 */
export const SKILL_LIBRARY: readonly SkillLibraryEntry[] = [
  // ===== A级技能 (选4) =====
  {
    id: 'a01',
    name: '圣剑一闪',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗2MP，对单体造成25伤害，无视5点护盾。',
    cost: { mp: 2 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'damage', params: { value: 25, pierceShield: 5 } },
    ],
  },
  {
    id: 'a02',
    name: '守护结界',
    skillClass: 'A',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'on_damage',
    description: '受到伤害时，抵消15点伤害。冷却2回合。',
    cooldown: 2,
    targetType: 'self',
    effects: [
      { effectType: 'shield', params: { value: 15 } },
    ],
  },
  {
    id: 'a03',
    name: '生命汲取',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗3MP，对单体造成15伤害并回复等量HP。',
    cost: { mp: 3 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'damage', params: { value: 15 } },
      { effectType: 'heal', params: { value: 15, target: 'self' } },
    ],
  },
  {
    id: 'a04',
    name: '战术侦查',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗1MP，查看目标手牌数量和HP，并抽1张牌。',
    cost: { mp: 1 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'vision', params: { reveal: ['handCount', 'hp'] } },
      { effectType: 'draw', params: { count: 1, target: 'self' } },
    ],
  },
  {
    id: 'a05',
    name: '迅捷突袭',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗2MP，移动到相邻区域并对该区域一名玩家造成20伤害。',
    cost: { mp: 2 },
    cooldown: 1,
    targetType: 'single',
    effects: [
      { effectType: 'move', params: { type: 'adjacent' } },
      { effectType: 'damage', params: { value: 20 } },
    ],
    tags: ['movement', 'damage'],
  },
  {
    id: 'a06',
    name: '神圣护佑',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗3MP，为自身附加30点护盾，持续2回合。',
    cost: { mp: 3 },
    cooldown: 2,
    targetType: 'self',
    effects: [
      { effectType: 'shield', params: { value: 30, duration: 2 } },
    ],
  },
  {
    id: 'a07',
    name: '命运抽签',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗1MP，从牌堆抽3张牌，然后弃1张。',
    cost: { mp: 1 },
    cooldown: 1,
    targetType: 'self',
    effects: [
      { effectType: 'draw', params: { count: 3, target: 'self' } },
      { effectType: 'discard', params: { count: 1, target: 'self', choice: 'player' } },
    ],
  },
  {
    id: 'a08',
    name: '破甲一击',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗2MP，对单体造成15伤害并移除目标所有护盾。',
    cost: { mp: 2 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'removeShield', params: {} },
      { effectType: 'damage', params: { value: 15 } },
    ],
  },
  {
    id: 'a09',
    name: '烽火连天',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗4MP，对当前区域所有敌人造成15伤害。',
    cost: { mp: 4 },
    cooldown: 2,
    targetType: 'area',
    effects: [
      { effectType: 'damage', params: { value: 15, aoe: true } },
    ],
  },
  {
    id: 'a10',
    name: '战地救护',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗2MP，回复自身或同区域友军30HP。',
    cost: { mp: 2 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'heal', params: { value: 30 } },
    ],
  },
  {
    id: 'a11',
    name: '暗影潜行',
    skillClass: 'A',
    rarity: 'rare',
    type: 'triggered',
    triggerTiming: 'on_move',
    description: '移动后进入隐匿状态，下次受击前不可被侦查发现。冷却3回合。',
    cooldown: 3,
    targetType: 'self',
    effects: [
      { effectType: 'stealth', params: { duration: 'until_hit' } },
    ],
    tags: ['stealth'],
  },
  {
    id: 'a12',
    name: '反击风暴',
    skillClass: 'A',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'on_damage',
    description: '受到击牌伤害时，自动对攻击者反弹10伤害。冷却1回合。',
    cooldown: 1,
    targetType: 'self',
    effects: [
      { effectType: 'reflect', params: { value: 10 } },
    ],
  },

  // ===== B级技能 (选2) =====
  {
    id: 'b01',
    name: '坚韧意志',
    skillClass: 'B',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'on_damage',
    description: 'HP低于30%时，受到的伤害减少5点。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'damageReduction', params: { value: 5, condition: 'hp_below_30%' } },
    ],
  },
  {
    id: 'b02',
    name: '资源回收',
    skillClass: 'B',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'round_start',
    description: '每回合开始时，从弃牌堆随机回收1张牌到手牌。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'retrieveDiscard', params: { count: 1, random: true } },
    ],
  },
  {
    id: 'b03',
    name: '先手之利',
    skillClass: 'B',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '战斗阶段中，你的出击优先级+1。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'modifyPriority', params: { value: 1 } },
    ],
  },
  {
    id: 'b04',
    name: '补给线',
    skillClass: 'B',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'round_end',
    description: '回合结束时，若手牌少于3张，抽牌至3张。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'draw', params: { fillTo: 3, condition: 'hand_below_3' } },
    ],
  },
  {
    id: 'b05',
    name: '地利之势',
    skillClass: 'B',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '在有己方阵地的区域战斗时，造成的伤害+5。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'damageBonus', params: { value: 5, condition: 'own_outpost_in_region' } },
    ],
  },
  {
    id: 'b06',
    name: '鹰眼洞察',
    skillClass: 'B',
    rarity: 'rare',
    type: 'triggered',
    triggerTiming: 'combat_before',
    description: '战斗开始前，可查看对手上一回合使用的技能。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'vision', params: { reveal: ['lastUsedSkills'] } },
    ],
  },
  {
    id: 'b07',
    name: '节能回路',
    skillClass: 'B',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'manual',
    description: '所有主动技能MP消耗-1（最低1）。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'mpReduction', params: { value: 1, minCost: 1 } },
    ],
  },
  {
    id: 'b08',
    name: '绝地反击',
    skillClass: 'B',
    rarity: 'rare',
    type: 'triggered',
    triggerTiming: 'on_damage',
    description: 'HP首次降至50%以下时，立即回复15HP并抽2张牌。每场战斗限1次。',
    cooldown: 0,
    charges: 1,
    targetType: 'self',
    effects: [
      { effectType: 'heal', params: { value: 15, target: 'self' } },
      { effectType: 'draw', params: { count: 2, target: 'self' } },
    ],
    tags: ['once_per_combat'],
  },

  // ===== 奈亚子（潜行吧！奈亚子）=====
  //
  // 卡牌型技能说明:
  //   cardCount: N  → 组卡时往牌库加入N张特殊击牌
  //   cardColor      → 加入的卡牌颜色
  //   type: 'active' + triggerTiming: 'on_strike'  → 该卡被当作攻击打出时触发 effects
  //   非卡牌型技能（被动/宝具）不设 cardCount

  {
    id: 'nyaruko_physics_sword',
    name: '物理学圣剑',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'on_strike',   // 作为击牌打出时触发
    description: '[卡牌1][无色] 攻击使用时，直至此次攻击完成结算前，所有角色不能从牌堆获取牌。',
    flavorText: '奈亚子（潜行吧！奈亚子）',
    cooldown: 0,
    targetType: 'single',
    cardCount: 1,
    cardColor: 'colorless',
    tags: ['attack_modifier', 'source:nyaruko'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'lockDraw', flagValue: true, target: 'global' } },
    ],
  },
  {
    id: 'nyaruko_cosmic_bomb',
    name: '亵渎之宇宙炸弹',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'on_strike',   // 作为击牌打出时触发
    description: '[卡牌1][无色] 须额外消耗3张手牌+3MP，对一名其他组角色进行无色攻击，造成伤害基准×3真实伤害，响应难度4。',
    flavorText: '奈亚子（潜行吧！奈亚子）',
    cost: { mp: 3 },
    cooldown: 0,
    targetType: 'single',
    cardCount: 1,
    cardColor: 'colorless',
    tags: ['true_damage', 'source:nyaruko'],
    effects: [
      { effectType: 'discard', params: { count: 3, target: 'self', choice: true } },
      { effectType: 'trueDamage', params: { multiplier: 3, basedOn: 'baseDamage' } },
      { effectType: 'modifyResponseDifficulty', params: { value: 4 } },
    ],
  },
  {
    id: 'nyaruko_infinite_joker',
    name: '无限的joker',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'standby',     // 备战阶段手动使用（非卡牌型，直接施放）
    description: '{高稀有度} <1MP> 备战环节，将X张[临时][抹消]无色普通牌加入手牌，X=已击杀从者数+1。',
    flavorText: '奈亚子（潜行吧！奈亚子）',
    cost: { mp: 1 },
    cooldown: 0,
    targetType: 'self',
    // 不是卡牌型，不设 cardCount — 直接施放生成临时牌
    tags: ['card_generation', 'source:nyaruko'],
    effects: [
      { effectType: 'addTempCardByKills', params: { color: 'colorless', baseCount: 1, erased: true } },
    ],
  },
  {
    id: 'nyaruko_cqc_108',
    name: '宇宙CQC壹佰〇捌式',
    skillClass: 'A',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'combat_before',  // 战斗开始时被动激活
    description: '[被动] 你的无色攻击指定唯一目标后，该目标不能使用其手中颜色最多的牌进行响应。',
    flavorText: '奈亚子（潜行吧！奈亚子）',
    cooldown: 0,
    targetType: 'self',
    tags: ['response_lock', 'source:nyaruko'],
    effects: [
      { effectType: 'lockMajorityColorResponse', params: {} },
    ],
  },
  {
    id: 'nyaruko_crawling_chaos',
    name: '伏行之混沌',
    skillClass: 'B',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'action_before',  // 行动阶段开始前被动触发
    description: '{高稀有度}[被动] 行动点+1。每个行动阶段开始时，若所在地点无其他组角色，随机获得能力：(1)额外相邻移动 (2)侦查隐匿 (3)侦查+2/行动-1 (4)备战免费无色攻击(响应难度1)。',
    flavorText: '奈亚子（潜行吧！奈亚子）',
    cooldown: 0,
    targetType: 'self',
    tags: ['action_bonus', 'random', 'noble_phantasm', 'source:nyaruko'],
    effects: [
      { effectType: 'modifyActionPoints', params: { value: 1 } },
      { effectType: 'crawlingChaosRandom', params: {} },
    ],
  },
  {
    id: 'nyaruko_thousand_faces',
    name: '千面之神',
    skillClass: 'B',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'round_start',    // 回合开始时被动（实质游戏开始即永久生效）
    description: '{高稀有度}[被动] 游戏开始时展示宝具并公开完整卡面，实时同步变动。本宝具无法被替换。所有能力来源名称视为真名。',
    flavorText: '奈亚子（潜行吧！奈亚子）',
    cooldown: 0,
    targetType: 'self',
    tags: ['info_reveal', 'permanent', 'noble_phantasm', 'source:nyaruko'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'publicCardFace', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'skillIrreplaceable', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'unifySourceName', flagValue: true } },
    ],
  },

  // =====================================================
  // 亚历山德罗·迪·卡利奥斯特罗
  // =====================================================

  {
    id: 'cagliostro_eastern_martial',
    name: '东方武技',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '[CD1]<2MP> 进行一次蓝色普通攻击，响应难度1，造成贯穿伤害。',
    flavorText: '亚历山德罗·迪·卡利奥斯特罗',
    cost: { mp: 2 },
    cooldown: 1,
    targetType: 'single',
    tags: ['source:cagliostro'],
    effects: [
      { effectType: 'freeStrike', params: { color: 'blue' } },
      { effectType: 'modifyResponseDifficulty', params: { value: 1 } },
      { effectType: 'setFlag', params: { flag: 'piercingDamage', flagValue: true } },
    ],
  },
  {
    id: 'cagliostro_i_am_asara',
    name: '吾乃亚沙拉',
    skillClass: 'A',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '[被动] 战斗阶段开始时，获得2点临时AC；若你是当前地点唯一具有AC的角色，额外弃抽一张牌。',
    flavorText: '亚历山德罗·迪·卡利奥斯特罗',
    cooldown: 0,
    targetType: 'self',
    tags: ['ac', 'source:cagliostro'],
    effects: [
      { effectType: 'gainAC', params: { value: 2, target: 'self', temporary: true } },
      { effectType: 'conditionalRedraw', params: { condition: 'soleACHolder', count: 1 } },
    ],
  },
  {
    id: 'cagliostro_item_forge',
    name: '物品铸造（伪）',
    skillClass: 'A',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'preparation',
    description: '[被动] 准备阶段结束时，令你所在组任意角色摸一张牌，该牌本回合内视为具有[护盾]。',
    flavorText: '亚历山德罗·迪·卡利奥斯特罗',
    cooldown: 0,
    targetType: 'self',
    tags: ['shield', 'card_generation', 'source:cagliostro'],
    effects: [
      { effectType: 'draw', params: { count: 1, target: 'group_any' } },
      { effectType: 'setFlag', params: { flag: 'drawnCardHasShield', flagValue: true } },
    ],
  },
  {
    id: 'cagliostro_althotas',
    name: '阿尔托塔斯连续统',
    skillClass: 'A',
    rarity: 'rare',
    type: 'triggered',
    triggerTiming: 'on_damage',
    description: '{高稀有度}[被动] 每局限一次，受到致命伤害时防止之并移除本技能，回复MP上限×5点HP。',
    flavorText: '亚历山德罗·迪·卡利奥斯特罗',
    cooldown: 0,
    charges: 1,
    targetType: 'self',
    tags: ['prevent_death', 'source:cagliostro'],
    effects: [
      { effectType: 'preventDeath', params: { hpAfter: 1 } },
      { effectType: 'healByMpMax', params: { multiplier: 5 } },
      { effectType: 'setFlag', params: { flag: 'removeSelfAfterUse', flagValue: true } },
    ],
  },
  {
    id: 'cagliostro_chaos_order',
    name: '赐秩序以死亡，授普世以混沌',
    skillClass: 'B',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '{高稀有度}[充能7] 公屏解放，对所有其他组角色各进行一次响应难度1D4的颜色不明攻击（可用任意颜色响应），命中目标流失1D10 HP（分别投掷）。[被动] 备战环节获得1点充能且获得1点AC。',
    flavorText: '亚历山德罗·迪·卡利奥斯特罗',
    cooldown: 0,
    targetType: 'global',
    tags: ['noble_phantasm', 'charge', 'source:cagliostro'],
    effects: [
      { effectType: 'globalUnknownAttack', params: { responseDifficultyDice: '1d4', hpLossDice: '1d10' } },
    ],
  },
  {
    id: 'cagliostro_hero_slayer',
    name: '英雄大敌（伪）',
    skillClass: 'B',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'round_start',
    description: '[被动] 击杀从者时立即吸收灵基，灵基属性分配不受"三项各升一级"规则限制（总提升不超过三级）。',
    flavorText: '亚历山德罗·迪·卡利奥斯特罗',
    cooldown: 0,
    targetType: 'self',
    tags: ['noble_phantasm', 'kill_bonus', 'source:cagliostro'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'freeAttributeAllocation', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'maxAttributeLevels', flagValue: 3 } },
    ],
  },

  // =====================================================
  // 缇妲妮娅（仲夏夜之梦）
  // =====================================================

  {
    id: 'titania_mustard_seed',
    name: '芥子',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '{高稀有度}[被动] 战斗阶段内，每当通过普通攻击以外方式消耗MP时，回复MP消耗量×1的HP，每回合至多回复伤害基准×1点。',
    flavorText: '缇妲妮娅（仲夏夜之梦）',
    cooldown: 0,
    targetType: 'self',
    tags: ['heal', 'mp_related', 'source:titania'],
    effects: [
      { effectType: 'mpSpendHeal', params: { ratio: 1, capBasedOn: 'baseDamage', capMultiplier: 1 } },
    ],
  },
  {
    id: 'titania_spider_silk',
    name: '蛛丝',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '{高稀有度}[虚色卡牌2][蓝色] 攻击使用时按颜色触发：①无色=贯穿+响应难度+1；②蓝色=命中时目标获得2层蛛网缠绕；③其他颜色=结算后摸两张牌。',
    flavorText: '缇妲妮娅（仲夏夜之梦）',
    cooldown: 0,
    targetType: 'single',
    cardCount: 2,
    cardColor: 'blue',
    tags: ['virtual_color', 'debuff', 'source:titania'],
    effects: [
      { effectType: 'colorBranchAttack', params: {
        colorless: { piercing: true, responseDifficultyBonus: 1 },
        blue: { applyDebuff: 'spiderWeb', stacks: 2 },
        other: { drawAfter: 2 },
      }},
    ],
  },
  {
    id: 'titania_pea_blossom',
    name: '豌豆花',
    skillClass: 'A',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'preparation',
    description: '[被动] 除第一回合外，每个准备阶段结束时，若无额外MP则获得1点额外MP。',
    flavorText: '缇妲妮娅（仲夏夜之梦）',
    cooldown: 0,
    targetType: 'self',
    tags: ['mp_related', 'source:titania'],
    effects: [
      { effectType: 'conditionalExtraMp', params: { condition: 'noExtraMp', value: 1, skipFirstRound: true } },
    ],
  },
  {
    id: 'titania_moth',
    name: '小峨',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '[虚色卡牌1][绿色] 消耗2MP，获得4AC；当这部分AC同一阶段内耗尽时，可再次使用弃牌堆中的本卡。',
    flavorText: '缇妲妮娅（仲夏夜之梦）',
    cost: { mp: 2 },
    cooldown: 0,
    targetType: 'self',
    cardCount: 1,
    cardColor: 'green',
    tags: ['virtual_color', 'ac', 'source:titania'],
    effects: [
      { effectType: 'gainAC', params: { value: 4, target: 'self', trackedPool: true } },
      { effectType: 'setFlag', params: { flag: 'recycleOnACDepleted', flagValue: true } },
    ],
  },
  {
    id: 'titania_midsummer_night',
    name: '是夜浮生',
    skillClass: 'B',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'standby',
    description: '[CD5]<3MP+1蓝+1绿> 初始CD。备战环节，公开指定至多3处其他地点，若有其他组角色则拉入当前地点战斗（无备战环节），持续至战斗结束。',
    flavorText: '缇妲妮娅（仲夏夜之梦）',
    cost: { mp: 3 },
    cooldown: 5,
    targetType: 'area',
    tags: ['noble_phantasm', 'forced_combat', 'source:titania'],
    effects: [
      { effectType: 'discard', params: { count: 2, target: 'self', requiredColors: ['blue', 'green'] } },
      { effectType: 'pullToCombat', params: { maxLocations: 3, noStandby: true } },
    ],
  },
  {
    id: 'titania_dream_aria',
    name: '梦月咏叹调',
    skillClass: 'B',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '[虚色卡牌1][万黑双色] 攻击不造成伤害，命中角色随机弃至多3张手牌。消耗10MP，当前地点所有角色随机弃至剩1张。',
    flavorText: '缇妲妮娅（仲夏夜之梦）',
    cooldown: 0,
    targetType: 'single',
    cardCount: 1,
    cardColor: 'black',
    tags: ['virtual_color', 'discard', 'source:titania'],
    effects: [
      { effectType: 'noDamageStrike', params: {} },
      { effectType: 'forceDiscard', params: { count: 3, random: true, targetType: 'hit' } },
      { effectType: 'aoeForceDiscardToOne', params: { mpCost: 10, targetType: 'sameLocation' } },
    ],
  },

  // =====================================================
  // 铁鼠（阴阳师：百闻牌）
  // =====================================================

  {
    id: 'tesso_lucky_coin',
    name: '幸运钱币',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '[卡牌2][无色] 使用/丢弃/消耗时，投掷d6：≥4摸一张牌，=6再摸一张。',
    flavorText: '铁鼠（阴阳师：百闻牌）',
    cooldown: 0,
    targetType: 'self',
    cardCount: 2,
    cardColor: 'colorless',
    tags: ['random', 'card_generation', 'source:tesso'],
    effects: [
      { effectType: 'luckyDraw', params: { dice: 'd6', threshold: 4, bonusThreshold: 6 } },
    ],
  },
  {
    id: 'tesso_precious_rat',
    name: '有鼠如宝',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '{高稀有度}[被动] 无色普通攻击+2增伤。战斗阶段开始时，获得1张临时抹消无色普通牌（仅攻击/响应用）。',
    flavorText: '铁鼠（阴阳师：百闻牌）',
    cooldown: 0,
    targetType: 'self',
    tags: ['colorless', 'damage_bonus', 'source:tesso'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'colorlessDamageBonus', flagValue: 2 } },
      { effectType: 'addTempCard', params: { color: 'colorless', count: 1, erased: true, strikeOnly: true } },
    ],
  },
  {
    id: 'tesso_accumulate',
    name: '敛财',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'standby',
    description: '[CD3]<2MP> 备战环节，摸两张牌并展示，使其中有色普通牌本回合视为虚色卡牌。',
    flavorText: '铁鼠（阴阳师：百闻牌）',
    cost: { mp: 2 },
    cooldown: 3,
    targetType: 'self',
    tags: ['virtual_color', 'card_generation', 'source:tesso'],
    effects: [
      { effectType: 'draw', params: { count: 2, target: 'self' } },
      { effectType: 'setFlag', params: { flag: 'revealAndMakeVirtualColor', flagValue: true } },
    ],
  },
  {
    id: 'tesso_fortune_art',
    name: '生财有术',
    skillClass: 'A',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'combat_after',
    description: '[CD2] 每当进行无色攻击后，视为对同一目标再进行一次无色普通攻击。[被动] 受到≥3点伤害后本技能清除1点CD。',
    flavorText: '铁鼠（阴阳师：百闻牌）',
    cooldown: 2,
    targetType: 'self',
    tags: ['colorless', 'attack_modifier', 'source:tesso'],
    effects: [
      { effectType: 'freeStrike', params: { color: 'colorless', triggerOn: 'afterColorlessAttack' } },
      { effectType: 'setFlag', params: { flag: 'cdReductionOnDamage', flagValue: { threshold: 3, reduction: 1 } } },
    ],
  },
  {
    id: 'tesso_money_power',
    name: '钱多不压身',
    skillClass: 'B',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'round_start',
    description: '{高稀有度}[被动] 每使用/消耗一张无色牌后（含御主为宝具支付的消耗），本回合内+1增伤。',
    flavorText: '铁鼠（阴阳师：百闻牌）',
    cooldown: 0,
    targetType: 'self',
    tags: ['noble_phantasm', 'colorless', 'damage_bonus', 'source:tesso'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'colorlessUseDamageStack', flagValue: true } },
    ],
  },
  {
    id: 'tesso_windfall',
    name: '天降横财',
    skillClass: 'B',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '{高稀有度}[CD4]<3牌> 将3张临时抹消无色普通牌加入手中（仅攻击/响应用）。',
    flavorText: '铁鼠（阴阳师：百闻牌）',
    cooldown: 4,
    targetType: 'self',
    tags: ['noble_phantasm', 'colorless', 'card_generation', 'source:tesso'],
    effects: [
      { effectType: 'discard', params: { count: 3, target: 'self', choice: true } },
      { effectType: 'addTempCard', params: { color: 'colorless', count: 3, erased: true, strikeOnly: true } },
    ],
  },
]

/** 按ID索引 */
export const SKILL_LIBRARY_MAP: Record<string, SkillLibraryEntry> =
  Object.fromEntries(SKILL_LIBRARY.map(s => [s.id, s]))

/** 按等级分组 */
export const A_CLASS_SKILLS = SKILL_LIBRARY.filter(s => s.skillClass === 'A')
export const B_CLASS_SKILLS = SKILL_LIBRARY.filter(s => s.skillClass === 'B')
