import type { SkillLibraryEntry } from '../types/skill.js'

/**
 * 技能库 — 所有预定义技能
 * 接口模块化：每个技能通过 effects[] 定义效果链
 * 后续增加技能只需在此数组中追加条目
 */
export const SKILL_LIBRARY: readonly SkillLibraryEntry[] = [
  // ===== A级技能 (选4) =====
  {
    id: 'a01',
    name: '圣剑一闪',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗2MP，对单体造成25伤害，无视5点护盾。',
    cost: { mp: 2 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'damage', params: { value: 25, pierceShield: 5 } },
    ],
  },
  {
    id: 'a02',
    name: '守护结界',
    skillClass: 'A',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'on_damage',
    description: '受到伤害时，抵消15点伤害。冷却2回合。',
    cooldown: 2,
    targetType: 'self',
    effects: [
      { effectType: 'shield', params: { value: 15 } },
    ],
  },
  {
    id: 'a03',
    name: '生命汲取',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗3MP，对单体造成15伤害并回复等量HP。',
    cost: { mp: 3 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'damage', params: { value: 15 } },
      { effectType: 'heal', params: { value: 15, target: 'self' } },
    ],
  },
  {
    id: 'a04',
    name: '战术侦查',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗1MP，查看目标手牌数量和HP，并抽1张牌。',
    cost: { mp: 1 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'vision', params: { reveal: ['handCount', 'hp'] } },
      { effectType: 'draw', params: { count: 1, target: 'self' } },
    ],
  },
  {
    id: 'a05',
    name: '迅捷突袭',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗2MP，移动到相邻区域并对该区域一名玩家造成20伤害。',
    cost: { mp: 2 },
    cooldown: 1,
    targetType: 'single',
    effects: [
      { effectType: 'move', params: { type: 'adjacent' } },
      { effectType: 'damage', params: { value: 20 } },
    ],
    tags: ['movement', 'damage'],
  },
  {
    id: 'a06',
    name: '神圣护佑',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗3MP，为自身附加30点护盾，持续2回合。',
    cost: { mp: 3 },
    cooldown: 2,
    targetType: 'self',
    effects: [
      { effectType: 'shield', params: { value: 30, duration: 2 } },
    ],
  },
  {
    id: 'a07',
    name: '命运抽签',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗1MP，从牌堆抽3张牌，然后弃1张。',
    cost: { mp: 1 },
    cooldown: 1,
    targetType: 'self',
    effects: [
      { effectType: 'draw', params: { count: 3, target: 'self' } },
      { effectType: 'discard', params: { count: 1, target: 'self', choice: 'player' } },
    ],
  },
  {
    id: 'a08',
    name: '破甲一击',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗2MP，对单体造成15伤害并移除目标所有护盾。',
    cost: { mp: 2 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'removeShield', params: {} },
      { effectType: 'damage', params: { value: 15 } },
    ],
  },
  {
    id: 'a09',
    name: '烽火连天',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗4MP，对当前区域所有敌人造成15伤害。',
    cost: { mp: 4 },
    cooldown: 2,
    targetType: 'area',
    effects: [
      { effectType: 'damage', params: { value: 15, aoe: true } },
    ],
  },
  {
    id: 'a10',
    name: '战地救护',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '消耗2MP，回复自身或同区域友军30HP。',
    cost: { mp: 2 },
    cooldown: 0,
    targetType: 'single',
    effects: [
      { effectType: 'heal', params: { value: 30 } },
    ],
  },
  {
    id: 'a11',
    name: '暗影潜行',
    skillClass: 'A',
    rarity: 'rare',
    type: 'triggered',
    triggerTiming: 'on_move',
    description: '移动后进入隐匿状态，下次受击前不可被侦查发现。冷却3回合。',
    cooldown: 3,
    targetType: 'self',
    effects: [
      { effectType: 'stealth', params: { duration: 'until_hit' } },
    ],
    tags: ['stealth'],
  },
  {
    id: 'a12',
    name: '反击风暴',
    skillClass: 'A',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'on_damage',
    description: '受到击牌伤害时，自动对攻击者反弹10伤害。冷却1回合。',
    cooldown: 1,
    targetType: 'self',
    effects: [
      { effectType: 'reflect', params: { value: 10 } },
    ],
  },

  // ===== B级技能 (选2) =====
  {
    id: 'b01',
    name: '坚韧意志',
    skillClass: 'B',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'on_damage',
    description: 'HP低于30%时，受到的伤害减少5点。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'damageReduction', params: { value: 5, condition: 'hp_below_30%' } },
    ],
  },
  {
    id: 'b02',
    name: '资源回收',
    skillClass: 'B',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'round_start',
    description: '每回合开始时，从弃牌堆随机回收1张牌到手牌。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'retrieveDiscard', params: { count: 1, random: true } },
    ],
  },
  {
    id: 'b03',
    name: '先手之利',
    skillClass: 'B',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '战斗阶段中，你的出击优先级+1。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'modifyPriority', params: { value: 1 } },
    ],
  },
  {
    id: 'b04',
    name: '补给线',
    skillClass: 'B',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'round_end',
    description: '回合结束时，若手牌少于3张，抽牌至3张。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'draw', params: { fillTo: 3, condition: 'hand_below_3' } },
    ],
  },
  {
    id: 'b05',
    name: '地利之势',
    skillClass: 'B',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '在有己方阵地的区域战斗时，造成的伤害+5。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'damageBonus', params: { value: 5, condition: 'own_outpost_in_region' } },
    ],
  },
  {
    id: 'b06',
    name: '鹰眼洞察',
    skillClass: 'B',
    rarity: 'rare',
    type: 'triggered',
    triggerTiming: 'combat_before',
    description: '战斗开始前，可查看对手上一回合使用的技能。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'vision', params: { reveal: ['lastUsedSkills'] } },
    ],
  },
  {
    id: 'b07',
    name: '节能回路',
    skillClass: 'B',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'manual',
    description: '所有主动技能MP消耗-1（最低1）。',
    cooldown: 0,
    targetType: 'self',
    effects: [
      { effectType: 'mpReduction', params: { value: 1, minCost: 1 } },
    ],
  },
  {
    id: 'b08',
    name: '绝地反击',
    skillClass: 'B',
    rarity: 'rare',
    type: 'triggered',
    triggerTiming: 'on_damage',
    description: 'HP首次降至50%以下时，立即回复15HP并抽2张牌。每场战斗限1次。',
    cooldown: 0,
    charges: 1,
    targetType: 'self',
    effects: [
      { effectType: 'heal', params: { value: 15, target: 'self' } },
      { effectType: 'draw', params: { count: 2, target: 'self' } },
    ],
    tags: ['once_per_combat'],
  },

  // ===== 奈亚子（潜行吧！奈亚子）=====
  //
  // 卡牌型技能说明:
  //   cardCount: N  → 组卡时往牌库加入N张特殊击牌
  //   cardColor      → 加入的卡牌颜色
  //   type: 'active' + triggerTiming: 'on_strike'  → 该卡被当作攻击打出时触发 effects
  //   非卡牌型技能（被动/宝具）不设 cardCount

  {
    id: 'nyaruko_physics_sword',
    name: '物理学圣剑',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'on_strike',   // 作为击牌打出时触发
    description: '[卡牌1][无色] 攻击使用时，直至此次攻击完成结算前，所有角色不能从牌堆获取牌。',
    flavorText: '奈亚子（潜行吧！奈亚子）',
    cooldown: 0,
    targetType: 'single',
    cardCount: 1,
    cardColor: 'colorless',
    tags: ['attack_modifier', 'source:nyaruko'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'lockDraw', flagValue: true, target: 'global' } },
    ],
  },
  {
    id: 'nyaruko_cosmic_bomb',
    name: '亵渎之宇宙炸弹',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'on_strike',   // 作为击牌打出时触发
    description: '[卡牌1][无色] 须额外消耗3张手牌+3MP，对一名其他组角色进行无色攻击，造成伤害基准×3真实伤害，响应难度4。',
    flavorText: '奈亚子（潜行吧！奈亚子）',
    cost: { mp: 3 },
    cooldown: 0,
    targetType: 'single',
    cardCount: 1,
    cardColor: 'colorless',
    tags: ['true_damage', 'source:nyaruko'],
    effects: [
      { effectType: 'discard', params: { count: 3, target: 'self', choice: true } },
      { effectType: 'trueDamage', params: { multiplier: 3, basedOn: 'baseDamage' } },
      { effectType: 'modifyResponseDifficulty', params: { value: 4 } },
    ],
  },
  {
    id: 'nyaruko_infinite_joker',
    name: '无限的joker',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'standby',     // 备战阶段手动使用（非卡牌型，直接施放）
    description: '{高稀有度} <1MP> 备战环节，将X张[临时][抹消]无色普通牌加入手牌，X=已击杀从者数+1。',
    flavorText: '奈亚子（潜行吧！奈亚子）',
    cost: { mp: 1 },
    cooldown: 0,
    targetType: 'self',
    // 不是卡牌型，不设 cardCount — 直接施放生成临时牌
    tags: ['card_generation', 'source:nyaruko'],
    effects: [
      { effectType: 'addTempCardByKills', params: { color: 'colorless', baseCount: 1, erased: true } },
    ],
  },
  {
    id: 'nyaruko_cqc_108',
    name: '宇宙CQC壹佰〇捌式',
    skillClass: 'A',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'combat_before',  // 战斗开始时被动激活
    description: '[被动] 你的无色攻击指定唯一目标后，该目标不能使用其手中颜色最多的牌进行响应。',
    flavorText: '奈亚子（潜行吧！奈亚子）',
    cooldown: 0,
    targetType: 'self',
    tags: ['response_lock', 'source:nyaruko'],
    effects: [
      { effectType: 'lockMajorityColorResponse', params: {} },
    ],
  },
  {
    id: 'nyaruko_crawling_chaos',
    name: '伏行之混沌',
    skillClass: 'B',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'action_before',  // 行动阶段开始前被动触发
    description: '{高稀有度}[被动] 行动点+1。每个行动阶段开始时，若所在地点无其他组角色，随机获得能力：(1)额外相邻移动 (2)侦查隐匿 (3)侦查+2/行动-1 (4)备战免费无色攻击(响应难度1)。',
    flavorText: '奈亚子（潜行吧！奈亚子）',
    cooldown: 0,
    targetType: 'self',
    tags: ['action_bonus', 'random', 'noble_phantasm', 'source:nyaruko'],
    effects: [
      { effectType: 'modifyActionPoints', params: { value: 1 } },
      { effectType: 'crawlingChaosRandom', params: {} },
    ],
  },
  {
    id: 'nyaruko_thousand_faces',
    name: '千面之神',
    skillClass: 'B',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'round_start',    // 回合开始时被动（实质游戏开始即永久生效）
    description: '{高稀有度}[被动] 游戏开始时展示宝具并公开完整卡面，实时同步变动。本宝具无法被替换。所有能力来源名称视为真名。',
    flavorText: '奈亚子（潜行吧！奈亚子）',
    cooldown: 0,
    targetType: 'self',
    tags: ['info_reveal', 'permanent', 'noble_phantasm', 'source:nyaruko'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'publicCardFace', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'skillIrreplaceable', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'unifySourceName', flagValue: true } },
    ],
  },

  // =====================================================
  // 亚历山德罗·迪·卡利奥斯特罗
  // =====================================================

  {
    id: 'cagliostro_eastern_martial',
    name: '东方武技',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '[CD1]<2MP> 进行一次蓝色普通攻击，响应难度1，造成贯穿伤害。',
    flavorText: '亚历山德罗·迪·卡利奥斯特罗',
    cost: { mp: 2 },
    cooldown: 1,
    targetType: 'single',
    tags: ['source:cagliostro'],
    effects: [
      { effectType: 'freeStrike', params: { color: 'blue' } },
      { effectType: 'modifyResponseDifficulty', params: { value: 1 } },
      { effectType: 'setFlag', params: { flag: 'piercingDamage', flagValue: true } },
    ],
  },
  {
    id: 'cagliostro_i_am_asara',
    name: '吾乃亚沙拉',
    skillClass: 'A',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '[被动] 战斗阶段开始时，获得2点临时AC；若你是当前地点唯一具有AC的角色，额外弃抽一张牌。',
    flavorText: '亚历山德罗·迪·卡利奥斯特罗',
    cooldown: 0,
    targetType: 'self',
    tags: ['ac', 'source:cagliostro'],
    effects: [
      { effectType: 'gainAC', params: { value: 2, target: 'self', temporary: true } },
      { effectType: 'conditionalRedraw', params: { condition: 'soleACHolder', count: 1 } },
    ],
  },
  {
    id: 'cagliostro_item_forge',
    name: '物品铸造（伪）',
    skillClass: 'A',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'preparation',
    description: '[被动] 准备阶段结束时，令你所在组任意角色摸一张牌，该牌本回合内视为具有[护盾]。',
    flavorText: '亚历山德罗·迪·卡利奥斯特罗',
    cooldown: 0,
    targetType: 'self',
    tags: ['shield', 'card_generation', 'source:cagliostro'],
    effects: [
      { effectType: 'draw', params: { count: 1, target: 'group_any' } },
      { effectType: 'setFlag', params: { flag: 'drawnCardHasShield', flagValue: true } },
    ],
  },
  {
    id: 'cagliostro_althotas',
    name: '阿尔托塔斯连续统',
    skillClass: 'A',
    rarity: 'rare',
    type: 'triggered',
    triggerTiming: 'on_damage',
    description: '{高稀有度}[被动] 每局限一次，受到致命伤害时防止之并移除本技能，回复MP上限×5点HP。',
    flavorText: '亚历山德罗·迪·卡利奥斯特罗',
    cooldown: 0,
    charges: 1,
    targetType: 'self',
    tags: ['prevent_death', 'source:cagliostro'],
    effects: [
      { effectType: 'preventDeath', params: { hpAfter: 1 } },
      { effectType: 'healByMpMax', params: { multiplier: 5 } },
      { effectType: 'setFlag', params: { flag: 'removeSelfAfterUse', flagValue: true } },
    ],
  },
  {
    id: 'cagliostro_chaos_order',
    name: '赐秩序以死亡，授普世以混沌',
    skillClass: 'B',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '{高稀有度}[充能7] 公屏解放，对所有其他组角色各进行一次响应难度1D4的颜色不明攻击（可用任意颜色响应），命中目标流失1D10 HP（分别投掷）。[被动] 备战环节获得1点充能且获得1点AC。',
    flavorText: '亚历山德罗·迪·卡利奥斯特罗',
    cooldown: 0,
    targetType: 'global',
    tags: ['noble_phantasm', 'charge', 'source:cagliostro'],
    effects: [
      { effectType: 'globalUnknownAttack', params: { responseDifficultyDice: '1d4', hpLossDice: '1d10' } },
    ],
  },
  {
    id: 'cagliostro_hero_slayer',
    name: '英雄大敌（伪）',
    skillClass: 'B',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'round_start',
    description: '[被动] 击杀从者时立即吸收灵基，灵基属性分配不受"三项各升一级"规则限制（总提升不超过三级）。',
    flavorText: '亚历山德罗·迪·卡利奥斯特罗',
    cooldown: 0,
    targetType: 'self',
    tags: ['noble_phantasm', 'kill_bonus', 'source:cagliostro'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'freeAttributeAllocation', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'maxAttributeLevels', flagValue: 3 } },
    ],
  },

  // =====================================================
  // 缇妲妮娅（仲夏夜之梦）
  // =====================================================

  {
    id: 'titania_mustard_seed',
    name: '芥子',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '{高稀有度}[被动] 战斗阶段内，每当通过普通攻击以外方式消耗MP时，回复MP消耗量×1的HP，每回合至多回复伤害基准×1点。',
    flavorText: '缇妲妮娅（仲夏夜之梦）',
    cooldown: 0,
    targetType: 'self',
    tags: ['heal', 'mp_related', 'source:titania'],
    effects: [
      { effectType: 'mpSpendHeal', params: { ratio: 1, capBasedOn: 'baseDamage', capMultiplier: 1 } },
    ],
  },
  {
    id: 'titania_spider_silk',
    name: '蛛丝',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '{高稀有度}[虚色卡牌2][蓝色] 攻击使用时按颜色触发：①无色=贯穿+响应难度+1；②蓝色=命中时目标获得2层蛛网缠绕；③其他颜色=结算后摸两张牌。',
    flavorText: '缇妲妮娅（仲夏夜之梦）',
    cooldown: 0,
    targetType: 'single',
    cardCount: 2,
    cardColor: 'blue',
    tags: ['virtual_color', 'debuff', 'source:titania'],
    effects: [
      { effectType: 'colorBranchAttack', params: {
        colorless: { piercing: true, responseDifficultyBonus: 1 },
        blue: { applyDebuff: 'spiderWeb', stacks: 2 },
        other: { drawAfter: 2 },
      }},
    ],
  },
  {
    id: 'titania_pea_blossom',
    name: '豌豆花',
    skillClass: 'A',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'preparation',
    description: '[被动] 除第一回合外，每个准备阶段结束时，若无额外MP则获得1点额外MP。',
    flavorText: '缇妲妮娅（仲夏夜之梦）',
    cooldown: 0,
    targetType: 'self',
    tags: ['mp_related', 'source:titania'],
    effects: [
      { effectType: 'conditionalExtraMp', params: { condition: 'noExtraMp', value: 1, skipFirstRound: true } },
    ],
  },
  {
    id: 'titania_moth',
    name: '小峨',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '[虚色卡牌1][绿色] 消耗2MP，获得4AC；当这部分AC同一阶段内耗尽时，可再次使用弃牌堆中的本卡。',
    flavorText: '缇妲妮娅（仲夏夜之梦）',
    cost: { mp: 2 },
    cooldown: 0,
    targetType: 'self',
    cardCount: 1,
    cardColor: 'green',
    tags: ['virtual_color', 'ac', 'source:titania'],
    effects: [
      { effectType: 'gainAC', params: { value: 4, target: 'self', trackedPool: true } },
      { effectType: 'setFlag', params: { flag: 'recycleOnACDepleted', flagValue: true } },
    ],
  },
  {
    id: 'titania_midsummer_night',
    name: '是夜浮生',
    skillClass: 'B',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'standby',
    description: '[CD5]<3MP+1蓝+1绿> 初始CD。备战环节，公开指定至多3处其他地点，若有其他组角色则拉入当前地点战斗（无备战环节），持续至战斗结束。',
    flavorText: '缇妲妮娅（仲夏夜之梦）',
    cost: { mp: 3 },
    cooldown: 5,
    targetType: 'area',
    tags: ['noble_phantasm', 'forced_combat', 'source:titania'],
    effects: [
      { effectType: 'discard', params: { count: 2, target: 'self', requiredColors: ['blue', 'green'] } },
      { effectType: 'pullToCombat', params: { maxLocations: 3, noStandby: true } },
    ],
  },
  {
    id: 'titania_dream_aria',
    name: '梦月咏叹调',
    skillClass: 'B',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '[虚色卡牌1][万黑双色] 攻击不造成伤害，命中角色随机弃至多3张手牌。消耗10MP，当前地点所有角色随机弃至剩1张。',
    flavorText: '缇妲妮娅（仲夏夜之梦）',
    cooldown: 0,
    targetType: 'single',
    cardCount: 1,
    cardColor: 'black',
    tags: ['virtual_color', 'discard', 'source:titania'],
    effects: [
      { effectType: 'noDamageStrike', params: {} },
      { effectType: 'forceDiscard', params: { count: 3, random: true, targetType: 'hit' } },
      { effectType: 'aoeForceDiscardToOne', params: { mpCost: 10, targetType: 'sameLocation' } },
    ],
  },

  // =====================================================
  // 铁鼠（阴阳师：百闻牌）
  // =====================================================

  {
    id: 'tesso_lucky_coin',
    name: '幸运钱币',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '[卡牌2][无色] 使用/丢弃/消耗时，投掷d6：≥4摸一张牌，=6再摸一张。',
    flavorText: '铁鼠（阴阳师：百闻牌）',
    cooldown: 0,
    targetType: 'self',
    cardCount: 2,
    cardColor: 'colorless',
    tags: ['random', 'card_generation', 'source:tesso'],
    effects: [
      { effectType: 'luckyDraw', params: { dice: 'd6', threshold: 4, bonusThreshold: 6 } },
    ],
  },
  {
    id: 'tesso_precious_rat',
    name: '有鼠如宝',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '{高稀有度}[被动] 无色普通攻击+2增伤。战斗阶段开始时，获得1张临时抹消无色普通牌（仅攻击/响应用）。',
    flavorText: '铁鼠（阴阳师：百闻牌）',
    cooldown: 0,
    targetType: 'self',
    tags: ['colorless', 'damage_bonus', 'source:tesso'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'colorlessDamageBonus', flagValue: 2 } },
      { effectType: 'addTempCard', params: { color: 'colorless', count: 1, erased: true, strikeOnly: true } },
    ],
  },
  {
    id: 'tesso_accumulate',
    name: '敛财',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'standby',
    description: '[CD3]<2MP> 备战环节，摸两张牌并展示，使其中有色普通牌本回合视为虚色卡牌。',
    flavorText: '铁鼠（阴阳师：百闻牌）',
    cost: { mp: 2 },
    cooldown: 3,
    targetType: 'self',
    tags: ['virtual_color', 'card_generation', 'source:tesso'],
    effects: [
      { effectType: 'draw', params: { count: 2, target: 'self' } },
      { effectType: 'setFlag', params: { flag: 'revealAndMakeVirtualColor', flagValue: true } },
    ],
  },
  {
    id: 'tesso_fortune_art',
    name: '生财有术',
    skillClass: 'A',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'combat_after',
    description: '[CD2] 每当进行无色攻击后，视为对同一目标再进行一次无色普通攻击。[被动] 受到≥3点伤害后本技能清除1点CD。',
    flavorText: '铁鼠（阴阳师：百闻牌）',
    cooldown: 2,
    targetType: 'self',
    tags: ['colorless', 'attack_modifier', 'source:tesso'],
    effects: [
      { effectType: 'freeStrike', params: { color: 'colorless', triggerOn: 'afterColorlessAttack' } },
      { effectType: 'setFlag', params: { flag: 'cdReductionOnDamage', flagValue: { threshold: 3, reduction: 1 } } },
    ],
  },
  {
    id: 'tesso_money_power',
    name: '钱多不压身',
    skillClass: 'B',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'round_start',
    description: '{高稀有度}[被动] 每使用/消耗一张无色牌后（含御主为宝具支付的消耗），本回合内+1增伤。',
    flavorText: '铁鼠（阴阳师：百闻牌）',
    cooldown: 0,
    targetType: 'self',
    tags: ['noble_phantasm', 'colorless', 'damage_bonus', 'source:tesso'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'colorlessUseDamageStack', flagValue: true } },
    ],
  },
  {
    id: 'tesso_windfall',
    name: '天降横财',
    skillClass: 'B',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '{高稀有度}[CD4]<3牌> 将3张临时抹消无色普通牌加入手中（仅攻击/响应用）。',
    flavorText: '铁鼠（阴阳师：百闻牌）',
    cooldown: 4,
    targetType: 'self',
    tags: ['noble_phantasm', 'colorless', 'card_generation', 'source:tesso'],
    effects: [
      { effectType: 'discard', params: { count: 3, target: 'self', choice: true } },
      { effectType: 'addTempCard', params: { color: 'colorless', count: 3, erased: true, strikeOnly: true } },
    ],
  },

  // =====================================================
  // 小布（弈仙牌）
  // =====================================================

  {
    id: 'xiaobu_sharpen',
    name: '磨砺不止',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'standby',
    description: '{高稀有度}[被动][CD2] 备战环节，HP上限+2并回复2HP；可弃两张手牌清除一项技能1点CD。[CD4]<8HP> HP上限+4，回合结束时回复4HP。',
    flavorText: '小布（弈仙牌）',
    cooldown: 2,
    targetType: 'self',
    tags: ['hp_max', 'heal', 'cd_reduction', 'source:xiaobu'],
    effects: [
      { effectType: 'modifyHpMax', params: { value: 2 } },
      { effectType: 'heal', params: { value: 2, target: 'self' } },
      { effectType: 'optionalDiscardForCdClear', params: { discardCount: 2, cdReduction: 1 } },
    ],
  },
  {
    id: 'xiaobu_temper_body',
    name: '锻体不息',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '[卡牌3][红] 攻击使用时可消耗4HP替代1MP，或消耗4HP上限替代1动作。响应使用时HP上限+2。',
    flavorText: '小布（弈仙牌）',
    cooldown: 0,
    targetType: 'self',
    cardCount: 3,
    cardColor: 'red',
    tags: ['hp_cost', 'hp_max', 'source:xiaobu'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'hpSubstituteMP', flagValue: { hpCost: 4, mpSaved: 1 } } },
      { effectType: 'setFlag', params: { flag: 'hpMaxSubstituteAction', flagValue: { hpMaxCost: 4, actionSaved: 1 } } },
      { effectType: 'onResponseHpMaxUp', params: { value: 2 } },
    ],
  },
  {
    id: 'xiaobu_spirit_surge',
    name: '灵涌不竭',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '{高稀有度}[被动] 你的蓝命中/你被红命中时HP上限+1。[CD2]<8HP上限> 获得2点额外MP。',
    flavorText: '小布（弈仙牌）',
    cooldown: 2,
    targetType: 'self',
    tags: ['hp_max', 'mp_related', 'source:xiaobu'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'blueHitHpMaxUp', flagValue: 1 } },
      { effectType: 'setFlag', params: { flag: 'redHitByHpMaxUp', flagValue: 1 } },
    ],
  },
  {
    id: 'xiaobu_undying',
    name: '生机不灭',
    skillClass: 'A',
    rarity: 'normal',
    type: 'triggered',
    triggerTiming: 'on_damage',
    description: '[被动] 每局限一次，HP降至0以下时回复至16，HP上限+16，触发后失去本技能。',
    flavorText: '小布（弈仙牌）',
    cooldown: 0,
    charges: 1,
    targetType: 'self',
    tags: ['prevent_death', 'hp_max', 'source:xiaobu'],
    effects: [
      { effectType: 'preventDeath', params: { hpAfter: 16 } },
      { effectType: 'modifyHpMax', params: { value: 16 } },
      { effectType: 'setFlag', params: { flag: 'removeSelfAfterUse', flagValue: true } },
    ],
  },
  {
    id: 'xiaobu_xiuxuan',
    name: '修玄不泯',
    skillClass: 'B',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '[CD4]<2MP+2牌+4HP上限> 本回合+2增伤+2减伤，攻击按颜色触发：红=响应难度+1；蓝=被响应时回1MP；绿=HP上限+4。每次触发消耗1点增/减伤。',
    flavorText: '小布（弈仙牌）',
    cost: { mp: 2 },
    cooldown: 4,
    targetType: 'self',
    tags: ['noble_phantasm', 'damage_bonus', 'damage_reduction', 'source:xiaobu'],
    effects: [
      { effectType: 'discard', params: { count: 2, target: 'self', choice: true } },
      { effectType: 'setFlag', params: { flag: 'hpMaxCost', flagValue: 4 } },
      { effectType: 'amplify', params: { multiplier: 2, decayPerUse: true } },
      { effectType: 'damageReductionGain', params: { value: 2, decayPerUse: true } },
      { effectType: 'setFlag', params: { flag: 'xiuxuanColorEffects', flagValue: true } },
    ],
  },
  {
    id: 'xiaobu_hundred_kills',
    name: '百杀破境',
    skillClass: 'B',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '{高稀有度}[CD4]<4MP+16HP>或<16HP上限> 对同一目标连续六次无色攻击，结算期间所有角色不能使用令咒与自由能力。',
    flavorText: '小布（弈仙牌）',
    cost: { mp: 4 },
    cooldown: 4,
    targetType: 'single',
    tags: ['noble_phantasm', 'colorless', 'multi_attack', 'source:xiaobu'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'lockSecretKeysAndFree', flagValue: true, target: 'global' } },
      { effectType: 'multiStrike', params: { count: 6, color: 'colorless' } },
    ],
  },

  // =====================================================
  // 两仪式（根源接续）
  // =====================================================

  {
    id: 'shiki_cloud_shine',
    name: '云耀',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'standby',
    description: '{高稀有度}[被动][CD3] 备战环节，本回合战斗内：①无色攻击被响应时回1MP；②手中普通攻击可视为无色，命中时获得2AC。',
    flavorText: '两仪式（根源接续）',
    cooldown: 3,
    targetType: 'self',
    tags: ['colorless', 'ac', 'mp_related', 'source:shiki'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'colorlessRespondedMpRecovery', flagValue: 1 } },
      { effectType: 'setFlag', params: { flag: 'normalAsColorless', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'colorlessHitAcGain', flagValue: 2 } },
    ],
  },
  {
    id: 'shiki_yin_yang',
    name: '阴阳鱼',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'action_before',
    description: '[CD2]<3行动点> 行动阶段，获得1张临时阴牌和1张临时阳牌。阴：受攻击时消耗1MP弃置，响应难度-1。阳：攻击时消耗1MP弃置，响应难度+1。',
    flavorText: '两仪式（根源接续）',
    cooldown: 2,
    targetType: 'self',
    tags: ['card_generation', 'response_modifier', 'source:shiki'],
    effects: [
      { effectType: 'addTempCard', params: { color: 'colorless', count: 1, name: '阴', skillCard: true } },
      { effectType: 'addTempCard', params: { color: 'colorless', count: 1, name: '阳', skillCard: true } },
    ],
  },
  {
    id: 'shiki_root_access',
    name: '根源接续',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'standby',
    description: '{高稀有度}[被动][CD3] 备战环节，本回合战斗内：①攻击命中时目标随机一项技能失效至下轮结束；②每轮限一次，攻击被响应时消耗1MP追加无色攻击。',
    flavorText: '两仪式（根源接续）',
    cooldown: 3,
    targetType: 'self',
    tags: ['debuff', 'colorless', 'source:shiki'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'hitDisableRandomSkill', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'respondedFreeColorlessAttack', flagValue: { mpCost: 1, perRound: 1 } } },
    ],
  },
  {
    id: 'shiki_mystic_eyes',
    name: '直死之魔眼',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '{高稀有度}[被动] 你的无色攻击造成伤害时，目标额外减少该伤害一半的HP上限（向上取整）。',
    flavorText: '两仪式（根源接续）',
    cooldown: 0,
    targetType: 'self',
    tags: ['colorless', 'hp_max_reduction', 'source:shiki'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'colorlessDamageReduceHpMax', flagValue: { ratio: 0.5, roundUp: true } } },
    ],
  },
  {
    id: 'shiki_void_boundary',
    name: '无垢识·空之境界',
    skillClass: 'B',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '{高稀有度}[卡牌1][无色] 消耗2令咒，对当前地点所有非友方角色无色攻击：响应须使用全部手牌、御主不参与、伤害使HP恰好剩1、无视AC不可防止。全员响应则返还令咒。',
    flavorText: '两仪式（根源接续）',
    cooldown: 0,
    targetType: 'area',
    cardCount: 1,
    cardColor: 'colorless',
    tags: ['noble_phantasm', 'aoe', 'source:shiki'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'secretKeyCost', flagValue: 2 } },
      { effectType: 'aoeReduceToOneHp', params: { ignoreAC: true, unpreventable: true } },
      { effectType: 'setFlag', params: { flag: 'fullHandResponse', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'refundKeysIfAllRespond', flagValue: 2 } },
    ],
  },
  {
    id: 'shiki_consciousness_eyes',
    name: '唯识·直死之魔眼',
    skillClass: 'B',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'combat_before',
    description: '{高稀有度}<6HP(6HP+1令咒)> 战斗阶段开始时选择目标，本轮内攻击对其造伤时：[一段]返还MP消耗+下轮起动作+1；[二段]额外减少伤害一半HP上限（向下取整）。',
    flavorText: '两仪式（根源接续）',
    cooldown: 0,
    targetType: 'single',
    tags: ['noble_phantasm', 'hp_max_reduction', 'source:shiki'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'hpCost', flagValue: 6 } },
      { effectType: 'setFlag', params: { flag: 'consciousnessEyesTarget', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'phase1_mpRefund', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'phase1_nextRoundActionBonus', flagValue: 1 } },
      { effectType: 'setFlag', params: { flag: 'phase2_hpMaxReduction', flagValue: { ratio: 0.5, roundDown: true } } },
    ],
  },

  // =====================================================
  // 卡牌大师崔斯特（英雄联盟）
  // =====================================================

  {
    id: 'tf_loaded_dice',
    name: '灌铅骰子',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'round_start',
    description: '{高稀有度}[被动] 概率多选一效果改为指定触发哪项。[CD3] 摸两张牌，25%概率流失1MP，其余概率弃一张。',
    flavorText: '卡牌大师崔斯特（英雄联盟）',
    cooldown: 3,
    targetType: 'self',
    tags: ['random_override', 'card_generation', 'source:tf'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'overrideRandomChoice', flagValue: true } },
      { effectType: 'draw', params: { count: 2, target: 'self' } },
      { effectType: 'luckyDraw', params: { dice: 'd4', threshold: 2, bonusThreshold: 999 } },
    ],
  },
  {
    id: 'tf_wild_card',
    name: '万能牌',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '[卡牌1][万色] 不占手牌上限，使用无需消耗，可在消耗中替代至多2MP。',
    flavorText: '卡牌大师崔斯特（英雄联盟）',
    cooldown: 0,
    targetType: 'self',
    cardCount: 1,
    cardColor: 'rainbow',
    tags: ['mp_substitute', 'source:tf'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'noHandSlotCost', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'freeToPlay', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'mpSubstitute', flagValue: 2 } },
    ],
  },
  {
    id: 'tf_pick_card',
    name: '选牌',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'preparation',
    description: '{高稀有度}[被动] 准备阶段结束时摸三张牌，然后丢弃三张牌。',
    flavorText: '卡牌大师崔斯特（英雄联盟）',
    cooldown: 0,
    targetType: 'self',
    tags: ['card_filter', 'source:tf'],
    effects: [
      { effectType: 'draw', params: { count: 3, target: 'self' } },
      { effectType: 'discard', params: { count: 3, target: 'self', choice: true } },
    ],
  },
  {
    id: 'tf_card_trick',
    name: '卡牌骗术',
    skillClass: 'A',
    rarity: 'rare',
    type: 'triggered',
    triggerTiming: 'combat_after',
    description: '{高稀有度}[CD2]<2MP或8HP> 战斗阶段结束时，若本阶段交战且用过特殊牌，可从弃牌堆回收一张特殊牌（至下回合结束前不计手牌上限）。',
    flavorText: '卡牌大师崔斯特（英雄联盟）',
    cooldown: 2,
    targetType: 'self',
    tags: ['card_recovery', 'source:tf'],
    effects: [
      { effectType: 'retrieveDiscard', params: { count: 1, filter: 'special', noHandLimit: true, duration: 'nextRoundEnd' } },
    ],
  },
  {
    id: 'tf_duel_time',
    name: '决斗时间！',
    skillClass: 'B',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'combat_before',
    description: '[CD4] 战斗阶段开始时，若当前地点仅有两名从者（含自身），双方：不可攻击御主、+2增伤、特殊牌视为万色。',
    flavorText: '卡牌大师崔斯特（英雄联盟）',
    cooldown: 4,
    targetType: 'area',
    tags: ['noble_phantasm', 'duel', 'source:tf'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'duelMode', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'noMasterTarget', flagValue: true, target: 'duelBoth' } },
      { effectType: 'amplify', params: { multiplier: 2 } },
      { effectType: 'setFlag', params: { flag: 'specialCardsRainbow', flagValue: true, target: 'duelBoth' } },
    ],
  },
  {
    id: 'tf_destiny',
    name: '命运',
    skillClass: 'B',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'action_before',
    description: '{高稀有度}[CD3]<3行动点> 初始CD。选一组未以此选过的角色，获悉位置并整组移动至该位置（暂时不可见），然后三选一：①现身+宣战备战；②阶段结束现身+遭遇备战；③返回原位现身。',
    flavorText: '卡牌大师崔斯特（英雄联盟）',
    cooldown: 3,
    targetType: 'single',
    tags: ['noble_phantasm', 'movement', 'stealth', 'forced_combat', 'source:tf'],
    effects: [
      { effectType: 'vision', params: { reveal: 'targetGroupLocation' } },
      { effectType: 'move', params: { type: 'teleportToTarget' } },
      { effectType: 'stealth', params: {} },
      { effectType: 'setFlag', params: { flag: 'destinyChoice', flagValue: true } },
    ],
  },

  // =====================================================
  // 马夫蒂·纳比尤·艾林（闪光的哈萨维）
  // =====================================================

  {
    id: 'mafty_self_torture',
    name: '自我拷问',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '{高稀有度}[CD2][自由] 对自身8点真实伤害，摸三张牌。可过载：额外回复3MP，但取消自由、额外8真伤、下次CD时长翻倍。',
    flavorText: '马夫蒂·纳比尤·艾林（闪光的哈萨维）',
    cooldown: 2,
    targetType: 'self',
    tags: ['self_damage', 'card_generation', 'overload', 'source:mafty'],
    effects: [
      { effectType: 'trueDamage', params: { multiplier: 1, fixedValue: 8, targetSelf: true } },
      { effectType: 'draw', params: { count: 3, target: 'self' } },
      { effectType: 'setFlag', params: { flag: 'overloadOption', flagValue: { extraMp: 3, extraDamage: 8, cdDoubled: true, loseFree: true } } },
    ],
  },
  {
    id: 'mafty_flash',
    name: '闪光',
    skillClass: 'A',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'round_start',
    description: '[被动] 你造成和受到的伤害+X，X初始为1，每回合结束时从-2~3中随机一个整数。',
    flavorText: '马夫蒂·纳比尤·艾林（闪光的哈萨维）',
    cooldown: 0,
    targetType: 'self',
    tags: ['random', 'damage_modifier', 'source:mafty'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'flashDamageModifier', flagValue: 1 } },
      { effectType: 'setFlag', params: { flag: 'flashRandomRange', flagValue: { min: -2, max: 3 } } },
    ],
  },
  {
    id: 'mafty_newtype',
    name: '新人类',
    skillClass: 'A',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '[被动] A形态：你造成伤害时令目标弃一张牌，成功弃牌时/回合结束切换至B。B形态：你受到伤害时你弃一张牌，成功弃牌时/回合结束切换至A。双形态技能。',
    flavorText: '马夫蒂·纳比尤·艾林（闪光的哈萨维）',
    cooldown: 0,
    targetType: 'self',
    tags: ['dual_form', 'discard', 'source:mafty'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'dualForm', flagValue: 'A' } },
      { effectType: 'setFlag', params: { flag: 'formA_onDealDamage_forceDiscard', flagValue: 1 } },
      { effectType: 'setFlag', params: { flag: 'formB_onTakeDamage_selfDiscard', flagValue: 1 } },
    ],
  },
  {
    id: 'mafty_full_burst',
    name: '全弹发射',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '{高稀有度}[被动] A形态：攻击未命中时消耗4HP或1MP追加无色攻击，消耗HP时/回合结束切B。B形态：攻击命中时消耗4HP或1MP追加无色攻击，消耗HP时/回合结束切A。双形态技能。',
    flavorText: '马夫蒂·纳比尤·艾林（闪光的哈萨维）',
    cooldown: 0,
    targetType: 'self',
    tags: ['dual_form', 'colorless', 'multi_attack', 'source:mafty'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'dualForm', flagValue: 'A' } },
      { effectType: 'setFlag', params: { flag: 'formA_onMiss_freeColorless', flagValue: { hpCost: 4, mpCost: 1 } } },
      { effectType: 'setFlag', params: { flag: 'formB_onHit_freeColorless', flagValue: { hpCost: 4, mpCost: 1 } } },
    ],
  },
  {
    id: 'mafty_drop_operation',
    name: '降落行动',
    skillClass: 'B',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'action_before',
    description: '[CD6]<3行动点+3MP> 行动阶段，移动至任一地点，遭遇则强制备战（你宣战对方迎战），然后选三项（可重复）：①免费攻击一个目标；②切换一项双形态技能并锁定本回合；③摸一张牌。',
    flavorText: '马夫蒂·纳比尤·艾林（闪光的哈萨维）',
    cost: { mp: 3 },
    cooldown: 6,
    targetType: 'global',
    tags: ['noble_phantasm', 'movement', 'forced_combat', 'dual_form', 'source:mafty'],
    effects: [
      { effectType: 'move', params: { type: 'teleportAnywhere' } },
      { effectType: 'setFlag', params: { flag: 'forcedEncounterWar', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'dropOperationChoices', flagValue: 3 } },
    ],
  },
  {
    id: 'mafty_guided_missile',
    name: '浮游导弹',
    skillClass: 'B',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '{高稀有度}[卡牌3][红][自由] 响应使用或弃置进入弃牌堆时，可选：①获得1点临时额外MP；②摸一张牌。',
    flavorText: '马夫蒂·纳比尤·艾林（闪光的哈萨维）',
    cooldown: 0,
    targetType: 'self',
    cardCount: 3,
    cardColor: 'red',
    tags: ['noble_phantasm', 'card_generation', 'mp_related', 'source:mafty'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'onDiscardChoice', flagValue: [
        { id: 'extraMp', label: '获得1点临时额外MP' },
        { id: 'drawOne', label: '摸一张牌' },
      ]}},
    ],
  },

  // =====================================================
  // 乌莎哈（暗堕型妖精）
  // =====================================================

  {
    id: 'usaha_fantasy_fortress',
    name: '幻想/至形极城',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '{高稀有度}[被动] 当前地点有自己据点时+2减伤，触发3次后减伤失效且受到的攻击响应难度-3（最低1），持续至回合结束。',
    flavorText: '乌莎哈（暗堕型妖精）',
    cooldown: 0,
    targetType: 'self',
    tags: ['outpost', 'damage_reduction', 'source:usaha'],
    effects: [
      { effectType: 'damageReductionGain', params: { value: 2, condition: 'hasOutpostHere', maxTriggers: 3 } },
      { effectType: 'setFlag', params: { flag: 'afterReductionDepletedResponsePenalty', flagValue: -3 } },
    ],
  },
  {
    id: 'usaha_mobility',
    name: '幻想/最机动性',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'combat_before',
    description: '[CD1][自由] 战斗阶段内每轮开始时可执行一项（正常消耗动作）：①普通攻击；②使用一项技能/宝具（不带自由或额外动作消耗）。',
    flavorText: '乌莎哈（暗堕型妖精）',
    cooldown: 1,
    targetType: 'self',
    tags: ['free', 'extra_action', 'source:usaha'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'roundStartFreeAction', flagValue: { attack: true, skill: true, noFreeOrExtraAction: true } } },
    ],
  },
  {
    id: 'usaha_hyper_dust',
    name: '虚拟/超想灰尘',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '[CD3]<3MP> 有据点=本回合+3增伤；无据点=立即建立临时据点（不占上限）。',
    flavorText: '乌莎哈（暗堕型妖精）',
    cost: { mp: 3 },
    cooldown: 3,
    targetType: 'self',
    tags: ['outpost', 'damage_bonus', 'source:usaha'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'outpostConditional', flagValue: { hasDamageBonus: 3, noneCreateTemp: true } } },
    ],
  },
  {
    id: 'usaha_gravity_shield',
    name: '虚拟/极防引力',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '[CD3]<4MP> 选择当前地点一名角色，本阶段其所有增伤减伤失效。有据点时返还2MP。',
    flavorText: '乌莎哈（暗堕型妖精）',
    cost: { mp: 4 },
    cooldown: 3,
    targetType: 'single',
    tags: ['outpost', 'debuff', 'source:usaha'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'nullifyBonusAndReduction', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'refundMpIfOutpost', flagValue: 2 } },
    ],
  },
  {
    id: 'usaha_throne_breaker',
    name: '七彩/王位破坏',
    skillClass: 'B',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '[卡牌1][万色]<6MP+3有色牌> 对一名非友方角色三连击（红→蓝→绿），三色严格不同=伤害基准×2，三色严格同色=响应难度+1。',
    flavorText: '乌莎哈（暗堕型妖精）',
    cost: { mp: 6 },
    cooldown: 0,
    targetType: 'single',
    cardCount: 1,
    cardColor: 'rainbow',
    tags: ['noble_phantasm', 'multi_attack', 'source:usaha'],
    effects: [
      { effectType: 'discard', params: { count: 3, target: 'self', requiredColors: ['colored'] } },
      { effectType: 'multiStrike', params: { count: 3, colorSequence: ['red', 'blue', 'green'] } },
      { effectType: 'setFlag', params: { flag: 'tricolorBonus', flagValue: { allDifferent: { damageMultiplier: 2 }, allSame: { responseDifficultyBonus: 1 } } } },
    ],
  },
  {
    id: 'usaha_darkness',
    name: '黑暗/夜露死苦',
    skillClass: 'B',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '{高稀有度}[CD4]<4MP+3有色牌> 获得2点临时增伤（有据点+2/宝具未消耗御主MP+1），攻击时可消耗1点临时增伤使响应难度+1。',
    flavorText: '乌莎哈（暗堕型妖精）',
    cost: { mp: 4 },
    cooldown: 4,
    targetType: 'self',
    tags: ['noble_phantasm', 'outpost', 'damage_bonus', 'source:usaha'],
    effects: [
      { effectType: 'discard', params: { count: 3, target: 'self', requiredColors: ['colored'] } },
      { effectType: 'setFlag', params: { flag: 'tempDamageBonus', flagValue: 2 } },
      { effectType: 'setFlag', params: { flag: 'outpostExtraDamageBonus', flagValue: 2 } },
      { effectType: 'setFlag', params: { flag: 'noMasterMpExtraBonus', flagValue: 1 } },
      { effectType: 'setFlag', params: { flag: 'spendBonusForResponseDifficulty', flagValue: true } },
    ],
  },

  // =====================================================
  // 白狼战鬼（艾尔登法环）
  // =====================================================

  {
    id: 'wolf_divine_shadow',
    name: '神人之影',
    skillClass: 'A',
    rarity: 'rare',
    type: 'triggered',
    triggerTiming: 'on_damage',
    description: '{高稀有度}[CD1]<1MP> 被攻击时宣言颜色并展示牌堆顶：匹配=弃展示牌+不进CD+响应难度-1；不匹配=普通牌弃、特殊牌入手。',
    flavorText: '白狼战鬼（艾尔登法环）',
    cost: { mp: 1 },
    cooldown: 1,
    targetType: 'self',
    tags: ['response_modifier', 'reveal', 'source:wolf'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'declareColorRevealTop', flagValue: { onMatch: { responseDifficultyBonus: -1, noCd: true }, onMiss: { normalDiscard: true, specialToHand: true } } } },
    ],
  },
  {
    id: 'wolf_summon_steed',
    name: '召唤灵马',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'round_start',
    description: '{高稀有度}[被动] 游戏开始时将3张[托雷特的哨笛]加入牌组。[卡牌3][万色] 攻击/响应/消耗时须额外消耗1MP否则视为无色。可替代地点牌。',
    flavorText: '白狼战鬼（艾尔登法环）',
    cooldown: 0,
    targetType: 'self',
    cardCount: 3,
    cardColor: 'rainbow',
    tags: ['card_generation', 'movement', 'source:wolf'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'requireExtraMpOrColorless', flagValue: 1 } },
      { effectType: 'setFlag', params: { flag: 'substituteLocationCard', flagValue: true } },
    ],
  },
  {
    id: 'wolf_tarnished',
    name: '褪色者',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'round_start',
    description: '{高稀有度}[被动] 游戏开始时将3张[法环碎片]加入牌组。[卡牌3][无色][自由] 消耗1MP，本阶段/轮结束时抽1牌，抽到特殊牌展示回4HP，否则回1MP。',
    flavorText: '白狼战鬼（艾尔登法环）',
    cooldown: 0,
    targetType: 'self',
    cardCount: 3,
    cardColor: 'colorless',
    tags: ['card_generation', 'heal', 'source:wolf'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'delayedDrawWithBonus', flagValue: { specialHeal: 4, normalMpRecover: 1 } } },
    ],
  },
  {
    id: 'wolf_black_flame',
    name: '宵色黑焰',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '[CD2]<3MP或8HP> 对目标无色攻击，伤害基准×1，响应难度4，无视减伤和AC。',
    flavorText: '白狼战鬼（艾尔登法环）',
    cost: { mp: 3 },
    cooldown: 2,
    targetType: 'single',
    tags: ['colorless', 'true_damage', 'source:wolf'],
    effects: [
      { effectType: 'freeStrike', params: { color: 'colorless' } },
      { effectType: 'modifyResponseDifficulty', params: { value: 4 } },
      { effectType: 'setFlag', params: { flag: 'ignoreReductionAndAC', flagValue: true } },
    ],
  },
  {
    id: 'wolf_destined_death',
    name: '命定之死',
    skillClass: 'B',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'combat_before',
    description: '{高稀有度}[被动] 第二次命中同一从者时其HP上限降至一半（阶段结束返还）。对非御主造伤时添加1层[命定之死]，每轮结束流失层数/2HP。阶段结束清除。',
    flavorText: '白狼战鬼（艾尔登法环）',
    cooldown: 0,
    targetType: 'self',
    tags: ['noble_phantasm', 'hp_max_reduction', 'dot', 'source:wolf'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'secondHitHpMaxHalve', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'onDamageApplyDot', flagValue: { stackName: 'destinedDeath', perRoundDrain: 0.5, clearOnPhaseEnd: true } } },
    ],
  },
  {
    id: 'wolf_godslayer_sword',
    name: '狩猎神祇大剑',
    skillClass: 'B',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '{高稀有度}[卡牌1]<3MP+红蓝绿> 连续X次攻击（红→蓝→绿循环），X=max(1, (HP上限-当前HP)/8取整)，视为从手中使用的普通攻击（不消耗动作）。',
    flavorText: '白狼战鬼（艾尔登法环）',
    cost: { mp: 3 },
    cooldown: 0,
    targetType: 'single',
    cardCount: 1,
    cardColor: 'colorless',
    tags: ['noble_phantasm', 'multi_attack', 'source:wolf'],
    effects: [
      { effectType: 'discard', params: { count: 3, target: 'self', requiredColors: ['red', 'blue', 'green'] } },
      { effectType: 'multiStrike', params: { countFormula: 'max(1, floor((hpMax-hp)/8))', colorSequence: ['red', 'blue', 'green'] } },
    ],
  },

  // =====================================================
  // 五条悟（新宿决战）
  // =====================================================

  {
    id: 'gojo_no_limit',
    name: '无下限',
    skillClass: 'A',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '{高稀有度}<2牌>[自由] 直至本轮结束，响应普通攻击所需牌数-1（最低0）。',
    flavorText: '五条悟（新宿决战）',
    cooldown: 0,
    targetType: 'self',
    tags: ['free', 'response_modifier', 'source:gojo'],
    effects: [
      { effectType: 'discard', params: { count: 2, target: 'self', choice: true } },
      { effectType: 'setFlag', params: { flag: 'responseCardReduction', flagValue: 1 } },
    ],
  },
  {
    id: 'gojo_cursed_blue',
    name: '顺转术式-苍',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '[CD1]<2×MP> 对一名角色蓝色攻击，响应难度X。未命中则目标弃X张牌。（X=MP消耗/2）',
    flavorText: '五条悟（新宿决战）',
    cooldown: 1,
    targetType: 'single',
    tags: ['scalable', 'source:gojo'],
    effects: [
      { effectType: 'freeStrike', params: { color: 'blue' } },
      { effectType: 'setFlag', params: { flag: 'scalableResponseDifficulty', flagValue: { perMp: 2 } } },
      { effectType: 'setFlag', params: { flag: 'onMissForceDiscard', flagValue: { countMatchesX: true } } },
    ],
  },
  {
    id: 'gojo_cursed_red',
    name: '术式反转-赫',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'manual',
    description: '[CD1]<3×HP> 对一名角色红色攻击，响应难度X。未命中则目标流失X点MP。（X=HP消耗/3）',
    flavorText: '五条悟（新宿决战）',
    cooldown: 1,
    targetType: 'single',
    tags: ['scalable', 'hp_cost', 'source:gojo'],
    effects: [
      { effectType: 'freeStrike', params: { color: 'red' } },
      { effectType: 'setFlag', params: { flag: 'scalableResponseDifficulty', flagValue: { perHp: 3 } } },
      { effectType: 'setFlag', params: { flag: 'onMissMpDrain', flagValue: { countMatchesX: true } } },
    ],
  },
  {
    id: 'gojo_reverse_meltdown',
    name: '反转术式-修复熔断',
    skillClass: 'A',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'round_start',
    description: '{高稀有度}[被动] 所有带CD的技能可过载使用：下一次使用后不进CD，但取消自由、额外8真伤、CD翻倍。',
    flavorText: '五条悟（新宿决战）',
    cooldown: 0,
    targetType: 'self',
    tags: ['overload', 'source:gojo'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'globalOverloadOption', flagValue: { extraDamage: 8, cdDoubled: true, loseFree: true, nextUseNoCd: true } } },
    ],
  },
  {
    id: 'gojo_unlimited_void',
    name: '领域展开-无量空处',
    skillClass: 'B',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'manual',
    description: '{高稀有度}[CD9]<9MP(9牌)> 替换上初始CD4。一段：下轮结束前对你的攻击不结算，结束时各组受[9-X]次无色攻击（X=该组对你攻击次数,至多9）。二段：响应难度+1，离场者立即结算。',
    flavorText: '五条悟（新宿决战）',
    cost: { mp: 9 },
    cooldown: 9,
    targetType: 'self',
    tags: ['noble_phantasm', 'domain', 'source:gojo'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'domainAttackNullify', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'domainEndCounterAttack', flagValue: { baseCount: 9, colorless: true } } },
      { effectType: 'setFlag', params: { flag: 'domainPhase2', flagValue: { responseDifficultyBonus: 1, leaveTriggersEnd: true } } },
    ],
  },
  {
    id: 'gojo_hollow_purple',
    name: '虚式-茈',
    skillClass: 'B',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '{高稀有度}[卡牌1][万色][反制][被动] 游戏开始公示。若为起始手牌则摸1牌弃本牌。任一阶段开始使用<4MP+1令咒>：本阶段禁令咒和自由、额外消耗1令咒，自动反制对你组的无色攻击。',
    flavorText: '五条悟（新宿决战）',
    cost: { mp: 4 },
    cooldown: 0,
    targetType: 'self',
    cardCount: 1,
    cardColor: 'rainbow',
    tags: ['noble_phantasm', 'counter', 'source:gojo'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'publicOnGameStart', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'startingHandRedraw', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'secretKeyCost', flagValue: 1 } },
      { effectType: 'setFlag', params: { flag: 'phaseStartLockFreeAndKeys', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'autoCounterColorless', flagValue: true } },
    ],
  },

  // =====================================================
  // 赫兹尔·雷斯=巴巴罗萨·海雷丁
  // =====================================================

  {
    id: 'barbarossa_wind_rain',
    name: '风雨庇佑',
    skillClass: 'A',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'action_before',
    description: '[被动] 行动阶段开始时随机弃一张手牌：蓝色普通牌=本回合非蓝攻击响应难度-1（最低1）；绿色普通牌=临时敏捷+1级。',
    flavorText: '赫兹尔·雷斯=巴巴罗萨·海雷丁',
    cooldown: 0,
    targetType: 'self',
    tags: ['random', 'response_modifier', 'source:barbarossa'],
    effects: [
      { effectType: 'forceDiscard', params: { count: 1, random: true, target: 'self' } },
      { effectType: 'setFlag', params: { flag: 'blueDiscardResponseReduction', flagValue: { reduction: 1, minDifficulty: 1 } } },
      { effectType: 'setFlag', params: { flag: 'greenDiscardAgiBoost', flagValue: 1 } },
    ],
  },
  {
    id: 'barbarossa_gunfire_raid',
    name: '枪火劫掠',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'standby',
    description: '[CD4]<2同色牌+1MP> 备战环节，进行一次响应难度2的攻击（颜色=消耗牌色），伤害基准×2。未命中则目标弃两张牌。',
    flavorText: '赫兹尔·雷斯=巴巴罗萨·海雷丁',
    cost: { mp: 1 },
    cooldown: 4,
    targetType: 'single',
    tags: ['attack', 'source:barbarossa'],
    effects: [
      { effectType: 'discard', params: { count: 2, target: 'self', requiredColors: ['sameColor'] } },
      { effectType: 'freeStrike', params: { color: 'matchDiscarded' } },
      { effectType: 'modifyResponseDifficulty', params: { value: 2 } },
      { effectType: 'amplify', params: { multiplier: 2 } },
      { effectType: 'setFlag', params: { flag: 'onMissForceDiscard', flagValue: { count: 2 } } },
    ],
  },
  {
    id: 'barbarossa_treasure',
    name: '丰实宝藏',
    skillClass: 'A',
    rarity: 'normal',
    type: 'passive',
    triggerTiming: 'standby',
    description: '[被动][CD3] 备战环节，获得2点临时额外MP。',
    flavorText: '赫兹尔·雷斯=巴巴罗萨·海雷丁',
    cooldown: 3,
    targetType: 'self',
    tags: ['mp_related', 'source:barbarossa'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'tempExtraMp', flagValue: 2 } },
    ],
  },
  {
    id: 'barbarossa_ride_wind',
    name: '乘风借力',
    skillClass: 'A',
    rarity: 'normal',
    type: 'active',
    triggerTiming: 'action_before',
    description: '[CD3]<1MP+1行动点> 移动至可侦查到的一处地点，遭遇则对所有其他从者进行红色攻击并强制备战（你宣战对方迎战）。',
    flavorText: '赫兹尔·雷斯=巴巴罗萨·海雷丁',
    cost: { mp: 1 },
    cooldown: 3,
    targetType: 'area',
    tags: ['movement', 'forced_combat', 'source:barbarossa'],
    effects: [
      { effectType: 'move', params: { type: 'scoutRange' } },
      { effectType: 'setFlag', params: { flag: 'onEncounterAoeRedAttack', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'forcedEncounterWar', flagValue: true } },
    ],
  },
  {
    id: 'barbarossa_endless_cannon',
    name: '无尽炮火',
    skillClass: 'B',
    rarity: 'rare',
    type: 'active',
    triggerTiming: 'on_strike',
    description: '{高稀有度}[卡牌1]<4MP+地点牌> 公屏展示。消耗牌对应地点所有其他组角色受一次无来源红攻，响应难度2，伤害=回合数+伤害基准。战斗阶段内可重复使用（MP改为2）。',
    flavorText: '赫兹尔·雷斯=巴巴罗萨·海雷丁',
    cost: { mp: 4 },
    cooldown: 0,
    targetType: 'global',
    cardCount: 1,
    cardColor: 'colorless',
    tags: ['noble_phantasm', 'aoe', 'source:barbarossa'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'requireLocationCard', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'remoteAoeRedAttack', flagValue: { responseDifficulty: 2, damageFormula: 'turnNumber+baseDamage' } } },
      { effectType: 'setFlag', params: { flag: 'repeatableInCombat', flagValue: { mpCostOverride: 2 } } },
    ],
  },
  {
    id: 'barbarossa_pillars',
    name: '赫拉克勒斯之柱（占据为王）',
    skillClass: 'B',
    rarity: 'rare',
    type: 'passive',
    triggerTiming: 'standby',
    description: '{高稀有度}[被动] 受到无来源攻击时响应难度-1（最后结算）。备战环节，若该地点有至少一个据点，所有角色受一次无来源红攻，响应难度2，伤害=回合数+伤害基准。',
    flavorText: '赫兹尔·雷斯=巴巴罗萨·海雷丁',
    cooldown: 0,
    targetType: 'self',
    tags: ['noble_phantasm', 'outpost', 'aoe', 'source:barbarossa'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'sourcelessAttackResponseReduction', flagValue: 1 } },
      { effectType: 'setFlag', params: { flag: 'standbyOutpostAoeRedAttack', flagValue: { responseDifficulty: 2, damageFormula: 'turnNumber+baseDamage' } } },
    ],
  },

  // =====================================================
  // 路西法
  // =====================================================
  { id: 'lucifer_twelve_wings', name: '漆黑的十二翼', skillClass: 'A', rarity: 'rare', type: 'active', triggerTiming: 'on_strike',
    description: '{高稀有度}[卡牌1][红]<2MP> 响应难度1（持有12张时改为2）。攻击使用后复制入牌库，最多12张。',
    flavorText: '路西法', cost: { mp: 2 }, cooldown: 0, targetType: 'single', cardCount: 1, cardColor: 'red',
    tags: ['self_replicate', 'source:lucifer'],
    effects: [
      { effectType: 'modifyResponseDifficulty', params: { value: 1, upgradeAt12: 2 } },
      { effectType: 'setFlag', params: { flag: 'replicateCardToDeck', flagValue: { maxCopies: 12 } } },
    ],
  },
  { id: 'lucifer_pride', name: '傲慢大权', skillClass: 'A', rarity: 'normal', type: 'passive', triggerTiming: 'combat_before',
    description: '[被动] 你的红色攻击对当前地点所有角色（含自己和御主）进行攻击。',
    flavorText: '路西法', cooldown: 0, targetType: 'self',
    tags: ['aoe', 'self_damage', 'source:lucifer'],
    effects: [{ effectType: 'setFlag', params: { flag: 'redAttackAoeIncludeSelf', flagValue: true } }],
  },
  { id: 'lucifer_fallen_blood', name: '堕天之血憎', skillClass: 'A', rarity: 'normal', type: 'active', triggerTiming: 'manual',
    description: '[CD4]<2MP> 本轮内自动响应所有以你为目标的红色攻击。',
    flavorText: '路西法', cost: { mp: 2 }, cooldown: 4, targetType: 'self',
    tags: ['auto_respond', 'source:lucifer'],
    effects: [{ effectType: 'setFlag', params: { flag: 'autoRespondRed', flagValue: true } }],
  },
  { id: 'lucifer_morning_star', name: '堕落的晨星', skillClass: 'A', rarity: 'rare', type: 'passive', triggerTiming: 'round_start',
    description: '{高稀有度}[被动] 对你使用令咒时御主选两项效果，使用后御主自身受6点真实伤害。',
    flavorText: '路西法', cooldown: 0, targetType: 'self',
    tags: ['secret_key_modifier', 'source:lucifer'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'secretKeyDoubleChoice', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'secretKeyMasterDamage', flagValue: 6 } },
    ],
  },
  { id: 'lucifer_soul_contract', name: '灵魂契约', skillClass: 'B', rarity: 'rare', type: 'passive', triggerTiming: 'round_start',
    description: '{高稀有度}[被动] 游戏开始公示不可替换。每偶数回合御主选一项（不重复）：①+3增/减伤；②自动响应红攻；③各摸3牌+3额外MP；④御主受6666真伤，若存活则死亡。',
    flavorText: '路西法', cooldown: 0, targetType: 'self',
    tags: ['noble_phantasm', 'permanent', 'source:lucifer'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'publicCardFace', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'skillIrreplaceable', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'evenRoundMasterChoice', flagValue: { options: ['buff3', 'autoRespondRed', 'draw3mp3', 'killMaster'] } } },
    ],
  },
  { id: 'lucifer_nine_days', name: '九天九夜', skillClass: 'B', rarity: 'rare', type: 'passive', triggerTiming: 'round_start',
    description: '{高稀有度}[被动] 游戏开始公示不可替换。开启后持续9回合：①你造成伤害后目标弃1牌或流失4HP；②你受到伤害后你弃1牌或流失4HP。',
    flavorText: '路西法', cooldown: 0, targetType: 'self',
    tags: ['noble_phantasm', 'permanent', 'dot', 'source:lucifer'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'publicCardFace', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'skillIrreplaceable', flagValue: true } },
      { effectType: 'setFlag', params: { flag: 'nineDaysEffect', flagValue: { duration: 9, onDealDamage: 'discardOrLose4', onTakeDamage: 'discardOrLose4' } } },
    ],
  },

  // =====================================================
  // 凯德六号（命运2）
  // =====================================================
  { id: 'cayde_solar_tower', name: '高塔的烈阳', skillClass: 'A', rarity: 'normal', type: 'triggered', triggerTiming: 'on_damage',
    description: '[CD1]<3MP+1牌>[反制] 被高行动顺位角色攻击时反制，令其选：非蓝色攻击MP+2 或 弃两张牌。',
    flavorText: '凯德六号（命运2）', cost: { mp: 3 }, cooldown: 1, targetType: 'self',
    tags: ['counter', 'source:cayde'],
    effects: [
      { effectType: 'discard', params: { count: 1, target: 'self', choice: true } },
      { effectType: 'negateEffect', params: { negatedType: 'attack' } },
      { effectType: 'setFlag', params: { flag: 'counterChoice', flagValue: { option1: 'nonBlueMpCost+2', option2: 'discard2' } } },
    ],
  },
  { id: 'cayde_void_gift', name: '虚空的馈赠', skillClass: 'A', rarity: 'normal', type: 'active', triggerTiming: 'on_strike',
    description: '[卡牌1][蓝色]<2MP+1动> 弃至少1张手牌摸等量。弃≥2且颜色一致时回1MP。',
    flavorText: '凯德六号（命运2）', cost: { mp: 2 }, cooldown: 0, targetType: 'self', cardCount: 1, cardColor: 'blue',
    tags: ['card_filter', 'source:cayde'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'discardDrawEqual', flagValue: { minDiscard: 1, sameColorMpRefund: 1, sameColorMinCount: 2 } } },
    ],
  },
  { id: 'cayde_thunder_rush', name: '雷鸣的突入', skillClass: 'A', rarity: 'normal', type: 'active', triggerTiming: 'on_strike',
    description: '[卡牌2][绿色] 响应使用后可消耗1MP摸1牌，每回合至多以此法摸2张。',
    flavorText: '凯德六号（命运2）', cooldown: 0, targetType: 'self', cardCount: 2, cardColor: 'green',
    tags: ['card_generation', 'source:cayde'],
    effects: [{ effectType: 'setFlag', params: { flag: 'onResponseDrawMp', flagValue: { mpCost: 1, drawCount: 1, maxPerRound: 2 } } }],
  },
  { id: 'cayde_dusty_heart', name: '蒙尘的心象', skillClass: 'A', rarity: 'normal', type: 'active', triggerTiming: 'on_strike',
    description: '[卡牌2][红色] 攻击使用后可弃1牌摸1牌。',
    flavorText: '凯德六号（命运2）', cooldown: 0, targetType: 'self', cardCount: 2, cardColor: 'red',
    tags: ['card_filter', 'source:cayde'],
    effects: [{ effectType: 'setFlag', params: { flag: 'onStrikeDiscardDraw', flagValue: { discard: 1, draw: 1 } } }],
  },
  { id: 'cayde_golden_gun', name: '黎明-黄金枪', skillClass: 'B', rarity: 'normal', type: 'active', triggerTiming: 'manual',
    description: '[CD6]<6MP+6牌> 对目标三次红攻。按消耗中红牌数：<3=流失HP上限一半HP；=4=清2CD；=5=摸5牌；=6=响应难度+1。',
    flavorText: '凯德六号（命运2）', cost: { mp: 6 }, cooldown: 6, targetType: 'single',
    tags: ['noble_phantasm', 'multi_attack', 'source:cayde'],
    effects: [
      { effectType: 'discard', params: { count: 6, target: 'self', choice: true } },
      { effectType: 'multiStrike', params: { count: 3, color: 'red' } },
      { effectType: 'setFlag', params: { flag: 'goldenGunRedCountBonus', flagValue: true } },
    ],
  },
  { id: 'cayde_void_arrows', name: '流离-虚空箭矢', skillClass: 'B', rarity: 'rare', type: 'passive', triggerTiming: 'standby',
    description: '{高稀有度}[被动][CD2] 备战环节，所有参战组角色至下一战斗阶段结束：不可令咒强制脱战、+2增伤、宝具MP+2。',
    flavorText: '凯德六号（命运2）', cooldown: 2, targetType: 'global',
    tags: ['noble_phantasm', 'aoe_buff', 'source:cayde'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'noForceRetreat', flagValue: true, target: 'allCombatants' } },
      { effectType: 'amplify', params: { multiplier: 2 } },
      { effectType: 'setFlag', params: { flag: 'nobleMpCostIncrease', flagValue: 2, target: 'allCombatants' } },
    ],
  },

  // =====================================================
  // 苍蓝星（怪物猎人）
  // =====================================================
  { id: 'hunter_challenger', name: '挑战者Lv.0', skillClass: 'A', rarity: 'rare', type: 'passive', triggerTiming: 'combat_after',
    description: '{高稀有度}[被动] 伤害基准+等级/2（向下取整，初始0）。交战后未离开=等级+1。击杀从者=等级上限+3（初始上限10）。',
    flavorText: '苍蓝星（怪物猎人）', cooldown: 0, targetType: 'self',
    tags: ['scaling', 'damage_bonus', 'source:hunter'],
    effects: [{ effectType: 'setFlag', params: { flag: 'challengerLevel', flagValue: { level: 0, cap: 10, bonusPerLevel: 0.5, capPerKill: 3 } } }],
  },
  { id: 'hunter_sharp_blade', name: '刚刃研磨', skillClass: 'A', rarity: 'normal', type: 'active', triggerTiming: 'manual',
    description: '<1MP+2动> 本回合下一次攻击响应难度+1（不叠加）。',
    flavorText: '苍蓝星（怪物猎人）', cost: { mp: 1 }, cooldown: 0, targetType: 'self',
    tags: ['response_modifier', 'source:hunter'],
    effects: [{ effectType: 'modifyResponseDifficulty', params: { value: 1, nextAttackOnly: true, noStack: true } }],
  },
  { id: 'hunter_evade', name: '体术', skillClass: 'A', rarity: 'rare', type: 'passive', triggerTiming: 'round_start',
    description: '{高稀有度}[被动] 动作+2。免除其他技能宝具消耗中的动作需求（限<>内写明的动作，技能本身消耗的动作不免）。',
    flavorText: '苍蓝星（怪物猎人）', cooldown: 0, targetType: 'self',
    tags: ['action_bonus', 'source:hunter'],
    effects: [
      { effectType: 'modifyActions', params: { value: 2 } },
      { effectType: 'setFlag', params: { flag: 'exemptSkillActionCost', flagValue: true } },
    ],
  },
  { id: 'hunter_adrenaline', name: '火场怪力', skillClass: 'A', rarity: 'normal', type: 'passive', triggerTiming: 'combat_before',
    description: '[被动] 当前HP<HP上限1/3时+1减伤+2增伤。',
    flavorText: '苍蓝星（怪物猎人）', cooldown: 0, targetType: 'self',
    tags: ['low_hp', 'damage_bonus', 'damage_reduction', 'source:hunter'],
    effects: [{ effectType: 'setFlag', params: { flag: 'lowHpBonus', flagValue: { threshold: 1/3, damageBonus: 2, damageReduction: 1 } } }],
  },
  { id: 'hunter_dragon_arrow', name: '龙之箭', skillClass: 'B', rarity: 'normal', type: 'active', triggerTiming: 'on_strike',
    description: '[卡牌1][红]<X红+XMP+X动> X≥1。红攻，伤害基准×3X，无视AC和减伤。',
    flavorText: '苍蓝星（怪物猎人）', cooldown: 0, targetType: 'single', cardCount: 1, cardColor: 'red',
    tags: ['noble_phantasm', 'scalable', 'true_damage', 'source:hunter'],
    effects: [{ effectType: 'setFlag', params: { flag: 'scalableDamage', flagValue: { perX: { damageMultiplier: 3 }, ignoreAC: true, ignoreReduction: true } } }],
  },
  { id: 'hunter_phial', name: '填装瓶', skillClass: 'B', rarity: 'rare', type: 'active', triggerTiming: 'action_before',
    description: '{高稀有度}[CD3]<XMP+X牌+4行动点> 填装X瓶。<1动>消耗瓶为下次攻击加成：接击瓶(基准+1,上限10)、强击瓶(+2增伤,上限5)、麻痹/猛毒/睡眠/爆破瓶各有独立效果。',
    flavorText: '苍蓝星（怪物猎人）', cooldown: 3, targetType: 'self',
    tags: ['noble_phantasm', 'resource_management', 'source:hunter'],
    effects: [{ effectType: 'setFlag', params: { flag: 'phialSystem', flagValue: {
      types: ['impact','power','paralysis','poison','sleep','blast'],
      caps: { impact: 10, power: 5, paralysis: 2, poison: 2, sleep: 2, blast: 2 },
      fillCosts: { impact: 1, power: 2, paralysis: 3, poison: 3, sleep: 3, blast: 5 },
    }}}],
  },

  // =====================================================
  // vivy（萤石眼之歌）
  // =====================================================
  { id: 'vivy_high_freq', name: '高频音域·撕裂', skillClass: 'A', rarity: 'normal', type: 'active', triggerTiming: 'on_strike',
    description: '[卡牌2][红]<3MP> 对当前地点所有其他组角色红攻，响应难度2，命中目标下次技能MP+1。',
    flavorText: 'vivy（萤石眼之歌）', cost: { mp: 3 }, cooldown: 0, targetType: 'area', cardCount: 2, cardColor: 'red',
    tags: ['aoe', 'debuff', 'source:vivy'],
    effects: [
      { effectType: 'modifyResponseDifficulty', params: { value: 2 } },
      { effectType: 'setFlag', params: { flag: 'hitTargetNextSkillMpIncrease', flagValue: 1 } },
    ],
  },
  { id: 'vivy_cocoon', name: '自律演算·茧', skillClass: 'A', rarity: 'rare', type: 'triggered', triggerTiming: 'combat_after',
    description: '{高稀有度}[被动] 攻击被响应后可回16HP+获得[数据茧]牌，但须封印自身一项技能。数据茧：无色可任意色攻击/响应，攻击使用后解封一项。',
    flavorText: 'vivy（萤石眼之歌）', cooldown: 0, targetType: 'self',
    tags: ['heal', 'card_generation', 'seal', 'source:vivy'],
    effects: [
      { effectType: 'heal', params: { value: 16, target: 'self' } },
      { effectType: 'addTempCard', params: { color: 'colorless', count: 1, name: '数据茧', erased: true } },
      { effectType: 'setFlag', params: { flag: 'cocoonSealRequired', flagValue: true } },
    ],
  },
  { id: 'vivy_predict', name: '动作预演算', skillClass: 'A', rarity: 'normal', type: 'triggered', triggerTiming: 'on_damage',
    description: '[CD2]<2MP>[反制] 被绿色普通攻击时反制，视为对其进行绿攻，造成敏捷等级×1伤害。',
    flavorText: 'vivy（萤石眼之歌）', cost: { mp: 2 }, cooldown: 2, targetType: 'self',
    tags: ['counter', 'source:vivy'],
    effects: [
      { effectType: 'negateEffect', params: { negatedType: 'greenAttack' } },
      { effectType: 'freeStrike', params: { color: 'green' } },
      { effectType: 'setFlag', params: { flag: 'damageByAgiRank', flagValue: true } },
    ],
  },
  { id: 'vivy_combo', name: '钢铁之舞·连击协议', skillClass: 'A', rarity: 'normal', type: 'active', triggerTiming: 'on_strike',
    description: '[卡牌1][绿]<4MP> 消耗全部剩余X动作和Y额外MP，对同一目标进行min(X,Y)次绿攻。',
    flavorText: 'vivy（萤石眼之歌）', cost: { mp: 4 }, cooldown: 0, targetType: 'single', cardCount: 1, cardColor: 'green',
    tags: ['multi_attack', 'scalable', 'source:vivy'],
    effects: [{ effectType: 'multiStrike', params: { countFormula: 'min(remainingActions, remainingExtraMp)', color: 'green' } }],
  },
  { id: 'vivy_overload', name: '机体超载', skillClass: 'B', rarity: 'rare', type: 'passive', triggerTiming: 'combat_before',
    description: '{高稀有度}[被动] HP<HP上限一半时：伤害基准+4，攻击被响应流失8HP；攻击时可流失4HP使响应难度+1。',
    flavorText: 'vivy（萤石眼之歌）', cooldown: 0, targetType: 'self',
    tags: ['noble_phantasm', 'low_hp', 'self_damage', 'source:vivy'],
    effects: [{ effectType: 'setFlag', params: { flag: 'overloadPassive', flagValue: {
      threshold: 0.5, baseDamageBonus: 4, respondedHpLoss: 8, optionalHpForDifficulty: { hpCost: 4, bonus: 1 },
    }}}],
  },
  { id: 'vivy_fluorite_song', name: 'Fluorite Eye\'s Song：萤石哀歌', skillClass: 'B', rarity: 'rare', type: 'active', triggerTiming: 'on_strike',
    description: '{高稀有度}[卡牌1][万色]<8MP+16HP+1令咒> 公屏使用，当前地点所有角色的技能宝具等全部茧封至阶段结束（来源名含vivy的不受影响）。',
    flavorText: 'vivy（萤石眼之歌）', cost: { mp: 8 }, cooldown: 0, targetType: 'area', cardCount: 1, cardColor: 'rainbow',
    tags: ['noble_phantasm', 'seal', 'aoe', 'source:vivy'],
    effects: [
      { effectType: 'setFlag', params: { flag: 'hpCost', flagValue: 16 } },
      { effectType: 'setFlag', params: { flag: 'secretKeyCost', flagValue: 1 } },
      { effectType: 'setFlag', params: { flag: 'aoeCocoonSeal', flagValue: { excludeSource: 'vivy', duration: 'phaseEnd' } } },
    ],
  },
]

/** 按ID索引 */
export const SKILL_LIBRARY_MAP: Record<string, SkillLibraryEntry> =
  Object.fromEntries(SKILL_LIBRARY.map(s => [s.id, s]))

/** 按等级分组 */
export const A_CLASS_SKILLS = SKILL_LIBRARY.filter(s => s.skillClass === 'A')
export const B_CLASS_SKILLS = SKILL_LIBRARY.filter(s => s.skillClass === 'B')
